import { createSlice } from "@reduxjs/toolkit";

const ArchitectureSlice = createSlice({
    name:'architectures',
    initialState:[
    {
      id: 201,
      name: "Indus Valley Civilization",
      period: "Ancient",
      category: "Urban Architecture",
      location: "Harappa, Mohenjo-Daro",
      region: "North-West India",
      image: "https://i.pinimg.com/1200x/db/62/dc/db62dc97fd2d413459b10bc1b4260103.jpg",
      shortDescription:
        "One of the world’s earliest urban civilizations known for advanced town planning.",
      description:"Indus Valley Civilization was one of the world’s earliest urban civilizations, flourishing around 2500 BCE in the northwestern regions of the Indian subcontinent. It is known for its well-planned cities, advanced drainage systems, standardized bricks, skilled craftsmanship, and thriving trade networks.",
      historicalSignificance:
        "Showcases advanced drainage systems and grid planning.",
      architecturalFeatures: [
        "Grid-based city layout",
        "Advanced drainage system",
        "Brick houses",
      ],
      builtBy: "Indus Valley People",
      builtIn: "2500 BCE",
      isFavorite: false,
    },
    {
      id: 202,
      name: "Sanchi Stupa",
      period: "Ancient",
      category: "Stupa",
      location: "Madhya Pradesh",
      region: "Central India",
      image: "https://i.pinimg.com/1200x/7a/59/f9/7a59f907add61846e694eb6a5fbaef0b.jpg",
      shortDescription: "A Buddhist monument commissioned by Emperor Ashoka for worship.",
      description:"Sanchi Stupa is an ancient Buddhist monument built by Emperor Ashoka in the 3rd century BCE. It is renowned for its massive dome, intricately carved gateways, and as an important center of Buddhist art and architecture.",
      historicalSignificance: "One of the oldest stone structures in India.",
      architecturalFeatures: [
        "Hemispherical dome",
        "Toranas (gateways)",
        "Relief carvings",
      ],
      builtBy: "Emperor Ashoka",
      builtIn: "3rd Century BCE",
      isFavorite: false,
    },

    {
      id: 203,
      name: "Ajanta & Ellora Caves",
      period: "Ancient",
      category: "Rock-Cut Architecture",
      location: "Maharashtra",
      region: "Western India",
      image: "https://i.pinimg.com/1200x/c9/01/86/c901868fb22201c991135b17c4fa3085.jpg",
      shortDescription: "Ancient rock-cut caves, famous for sculptures and murals, attract visitors from the world.",
      description:"Ajanta Caves and Ellora Caves are UNESCO World Heritage Sites in Maharashtra, famous for their ancient rock-cut architecture. Ajanta Caves are known for beautiful Buddhist paintings and murals, while Ellora Caves showcase remarkable Buddhist, Hindu, and Jain temples carved into solid rock.",
      historicalSignificance:
        "Represents Buddhist, Hindu, and Jain traditions.",
      architecturalFeatures: [
        "Rock-cut temples",
        "Wall paintings",
        "Monolithic structures",
      ],
      builtBy: "Various Dynasties",
      builtIn: "2nd Century BCE – 6th Century CE",
      isFavorite: false,
    },

    {
      id: 204,
      name: "Ashokan Pillars",
      period: "Ancient",
      category: "Monument",
      location: "Across India",
      region: "Pan India",
      image: "https://i.pinimg.com/1200x/6c/6a/a3/6c6aa32957af5a054bf624c949153ec5.jpg",
      shortDescription: "Stone pillars, intricately carved and erected by Emperor Ashoka.",
      description:"Ashokan Pillars are a series of monumental stone columns erected by Emperor Ashoka in the 3rd century BCE across the Indian subcontinent. They are renowned for their polished sandstone finish, inscriptions promoting moral and ethical values, and the iconic Lion Capital, which is now India’s national emblem.",
      historicalSignificance:
        "Symbol of Mauryan power and Buddhist principles.",
      architecturalFeatures: [
        "Polished sandstone",
        "Lion capital",
        "Edicts inscribed",
      ],
      builtBy: "Emperor Ashoka",
      builtIn: "3rd Century BCE",
      isFavorite: false,
    },

    {
      id: 205,
      name: "Barabar Caves",
      period: "Ancient",
      category: "Cave Architecture",
      location: "Bihar",
      region: "Eastern India",
      image: "https://i.pinimg.com/736x/d7/58/e5/d758e5caacc1b56d686881101dcff2c7.jpg",
      shortDescription: "Oldest surviving rock-cut caves in India, known for their historical significance.",
      description:"Barabar Caves are the oldest surviving rock-cut caves in India, dating back to the Mauryan period (3rd century BCE). Known for their highly polished granite interiors, they were used by Ajivika monks and reflect early advancements in cave architecture.",
      historicalSignificance: "Dedicated to Ajivika monks.",
      architecturalFeatures: [
        "Highly polished interiors",
        "Simple rectangular chambers",
      ],
      builtBy: "Mauryan Empire",
      builtIn: "3rd Century BCE",
      isFavorite: false,
    },

    {
      id: 206,
      name: "Bhitargaon Temple",
      period: "Ancient",
      category: "Temple",
      location: "Uttar Pradesh",
      region: "North India",
      image: "https://i.pinimg.com/1200x/81/78/bd/8178bdddbf549fff7a8085d0ceb221df.jpg",
      shortDescription: "An example of Hindu temple architecture, and showcasing intricate carvings and design.",
      description:"Bhitargaon Temple is one of the oldest surviving brick temples in India, dating to the Gupta period (5th century CE). It is noted for its terracotta decorative panels and early Nagara-style temple architecture.",
      historicalSignificance: "One of the oldest brick temples in India.",
      architecturalFeatures: ["Brick construction", "Shikhara structure"],
      builtBy: "Gupta Dynasty",
      builtIn: "5th Century CE",
      isFavorite: false,
    },

    {
      id: 207,
      name: "Megalithic Structures",
      period: "Ancient",
      category: "Burial Architecture",
      location: "South India",
      region: "Southern India",
      image: "https://cdn.mos.cms.futurecdn.net/XRyDEA6dwNcqJRqbfaBhY.jpg",
      shortDescription: "Stone burial monuments from prehistoric times, built to honor the mark sacred spaces.",
      description:"Megalithic Structures are ancient monuments built using large stone blocks, dating back to the prehistoric period. In India, they are commonly found in South India and are associated with burial practices and memorial traditions of early communities. These structures include dolmens, stone circles, menhirs, and cairns, reflecting early engineering skills and cultural beliefs about life and death.",
      historicalSignificance: "Represents early burial practices.",
      architecturalFeatures: ["Large stone slabs", "Burial chambers"],
      builtBy: "Megalithic Communities",
      builtIn: "1000 BCE",
      isFavorite: false,
    },
    {
      id: 208,
      name: "Qutub Minar",
      period: "Medieval",
      category: "Indo-Islamic Monument",
      location: "Delhi",
      region: "North India",
      image: "https://i.pinimg.com/736x/ff/cd/ed/ffcded3b119ab7d731b689863eb1e49d.jpg",
      shortDescription: "Tallest brick minaret in the world, renowned for its architectural brilliance.",
      description:"Qutub Minar is a 73-meter-high minaret located in Delhi, built in 1193 by Qutb-ud-din Aibak. It is one of the tallest brick minarets in the world and is renowned for its Indo-Islamic architecture, intricate carvings, and Quranic inscriptions. It is also a UNESCO World Heritage Site.",
      historicalSignificance: "Symbol of Delhi Sultanate.",
      architecturalFeatures: ["Fluted red sandstone", "Arabic inscriptions"],
      builtBy: "Qutb-ud-din Aibak",
      builtIn: "12th Century",
      isFavorite: false,
    },

    {
      id: 209,
      name: "Jama Masjid",
      period: "Medieval",
      category: "Mosque",
      location: "Delhi",
      region: "North India",
      image: "https://i.pinimg.com/1200x/7b/b7/2f/7bb72ff3616f86428cb65060a1570c90.jpg",
      shortDescription: "One of the largest mosques in India, known for its graqnd architecture importance.",
      description:"Jama Masjid is one of the largest and most prominent mosques in India, built in the 17th century by Mughal emperor Shah Jahan. It is renowned for its grand courtyards, massive domes, tall minarets, and fine Mughal architectural style.",
      historicalSignificance: "Mughal architectural masterpiece.",
      architecturalFeatures: ["Large courtyard", "Marble domes"],
      builtBy: "Shah Jahan",
      builtIn: "17th Century",
      isFavorite: false,
    },

    {
      id: 210,
      name: "Gol Gumbaz",
      period: "Medieval",
      category: "Mausoleum",
      location: "Karnataka",
      region: "South India",
      image: "https://i.pinimg.com/1200x/0e/e6/b2/0ee6b2dceb2cd9ea60926c18270a31f7.jpg",
      shortDescription: "Famous for its massive and impressive dome, showcasing remarkable architectural skill.",
      description:"Gol Gumbaz is a magnificent 17th-century mausoleum in Bijapur (Vijayapura), built by Mohammed Adil Shah. It is famous for its massive dome—one of the largest in the world—and the unique Whispering Gallery, where even the faintest sound echoes clearly.",
      historicalSignificance: "Whispering gallery marvel.",
      architecturalFeatures: ["Largest dome in India", "Acoustic design"],
      builtBy: "Adil Shahi Dynasty",
      builtIn: "17th Century",
      isFavorite: false,
    },

    {
      id: 211,
      name: "Charminar",
      period: "Medieval",
      category: "Monument",
      location: "Hyderabad",
      region: "South India",
      image: "https://i.pinimg.com/736x/1a/62/c3/1a62c309f522284076611e89b4288742.jpg",
      shortDescription: "An iconic monument with four grand arches, celebrated for its architectural elegance.",
      description:"Charminar is a historic monument built in 1591 by Muhammad Quli Qutb Shah in Hyderabad. Known for its four grand minarets and Indo-Islamic architecture, it symbolizes the city’s heritage and was constructed to commemorate the end of a deadly plague.",
      historicalSignificance: "Symbol of Hyderabad city.",
      architecturalFeatures: ["Four minarets", "Indo-Islamic style"],
      builtBy: "Muhammad Quli Qutb Shah",
      builtIn: "16th Century",
      isFavorite: false,
    },

    {
      id: 212,
      name: "Nagara Style",
      period: "Medieval",
      category: "Temple Architecture Style",
      location: "North India",
      region: "North India",
      image: "https://thearchitectsdiary.com/wp-content/uploads/2023/12/Nagara-style-temple-Image-01-1024x768.webp",
      shortDescription: "A distinctive North Indian temple architectural style, with intricate carvings.",
      description:"Nagara Style is a major temple architecture style of North India, characterized by a curvilinear tower (shikhara) rising above the sanctum. These temples usually have a square base, intricate carvings, and emphasize vertical elevation, reflecting spiritual ascent and architectural elegance.",
      historicalSignificance: "Distinctive shikhara design.",
      architecturalFeatures: ["Curvilinear towers", "Garbhagriha"],
      builtBy: "Various Dynasties",
      builtIn: "Medieval Period",
      isFavorite: false,
    },

    {
      id: 213,
      name: "Dravidian Style",
      period: "Medieval",
      category: "Temple Architecture Style",
      location: "South India",
      region: "South India",
      image: "https://i.pinimg.com/736x/17/54/dd/1754dde891e3a4ea6fb5f4489821a7c8.jpg",
      shortDescription: "A South Indian temple style, known for towering gopurams and intricate carvings.",
      description:"Dravidian Style is a major temple architecture style of South India, characterized by pyramid-shaped towers (vimanas), large temple complexes, pillared halls, and grand entrance gateways called gopurams. These temples are richly decorated with sculptures and reflect the cultural and artistic achievements of ancient South Indian kingdoms.",
      historicalSignificance: "Large gopurams and temple complexes.",
      architecturalFeatures: ["Gopuram towers", "Pillared halls"],
      builtBy: "Chola & Pandya Dynasties",
      builtIn: "Medieval Period",
      isFavorite: false,
    },

    {
      id: 214,
      name: "Vesara Style",
      period: "Medieval",
      category: "Temple Architecture Style",
      location: "Deccan",
      region: "Central India",
      image: "https://pwonlyias.com/wp-content/uploads/2024/04/182-6620b4096a7e8.webp",
      shortDescription: "Blend of Nagara and Dravidian styles, known for unique architectural features.",
      description:"Vesara Style is a temple architecture style that blends features of both the Nagara (North Indian) and Dravidian (South Indian) styles. It is characterized by a balanced structure, ornate detailing, and a hybrid tower form, and was mainly developed in the Deccan region under the Chalukyas and later dynasties.",
      historicalSignificance: "Represents architectural fusion.",
      architecturalFeatures: ["Hybrid design", "Ornate carvings"],
      builtBy: "Chalukya Dynasty",
      builtIn: "Medieval Period",
      isFavorite: false,
    },

    {
      id: 215,
      name: "Red Fort",
      period: "Medieval",
      category: "Fort",
      location: "Delhi",
      region: "North India",
      image: "https://i.pinimg.com/736x/42/c5/c1/42c5c1eb9062b5317d303e41d1fc09eb.jpg",
      shortDescription: "A massive fort complex built in red sandstone, known for its grand historical importance.",
      description:"Red Fort is a historic Mughal fort built in 1648 by Emperor Shah Jahan in Delhi. Constructed with red sandstone, it is renowned for its massive walls, beautiful palaces, and Indo-Islamic architecture. It is a UNESCO World Heritage Site and a symbol of India’s rich history.",
      historicalSignificance: "Seat of Mughal power.",
      architecturalFeatures: ["Red sandstone walls", "Palace structures"],
      builtBy: "Shah Jahan",
      builtIn: "17th Century",
      isFavorite: false,
    },

    {
      id: 216,
      name: "Amer Fort",
      period: "Medieval",
      category: "Fort",
      location: "Rajasthan",
      region: "North India",
      image: "https://i.pinimg.com/1200x/b2/0b/97/b20b977813320fcb9524cc8d37a3049c.jpg",
      shortDescription: "A hilltop fort blending Rajput and Mughal styles, famous for its strategic location.",
      description:"Amer Fort is a majestic hilltop fort in Jaipur, built in the 16th century by Raja Man Singh I. It is known for its grand courtyards, intricate mirror work in the Sheesh Mahal, and a beautiful blend of Rajput and Mughal architectural styles.",
      historicalSignificance: "Royal residence of Rajput rulers.",
      architecturalFeatures: ["Mirror work", "Courtyards"],
      builtBy: "Raja Man Singh",
      builtIn: "16th Century",
      isFavorite: false,
    },

    {
      id: 217,
      name: "Hampi Monuments",
      period: "Medieval",
      category: "Temple Complex",
      location: "Karnataka",
      region: "South India",
      image: "https://i.pinimg.com/1200x/36/cf/f0/36cff03f24fabac7b7f9ac8334a0e70d.jpg",
      shortDescription: "The ruins of Vijayanagara Empire, showcasing its former grandeur brilliance.",
      description:"Hampi Monuments are the magnificent remains of the Vijayanagara Empire, dating from the 14th to 16th centuries. Located in Karnataka, they are known for grand temples, stone chariots, massive gateways, and intricate carvings. Hampi is a UNESCO World Heritage Site and showcases the architectural brilliance of medieval South India.",
      historicalSignificance: "UNESCO World Heritage Site.",
      architecturalFeatures: ["Stone temples", "Bazaar streets"],
      builtBy: "Vijayanagara Empire",
      builtIn: "14th Century",
      isFavorite: false,
    },
    {
      id:218,
      name: "Lotus Temple",
      period: "Modern",
      category: "Religious Monument",
      location: "Delhi",
      region: "North India",
      image: "https://i.pinimg.com/1200x/69/2f/e6/692fe6518686fca20d9c134cc9073445.jpg",
      shortDescription: "A modern architectural marvel shaped like a lotus, admired for its aesthetic appeal.",
      description:"Lotus Temple is a modern architectural landmark in New Delhi, completed in 1986. Shaped like a blooming lotus flower, it is a Bahá’í House of Worship open to people of all faiths and is admired for its serene atmosphere and innovative design.",
      historicalSignificance: "Symbol of unity and peace.",
      architecturalFeatures: ["Lotus-shaped design", "White marble structure"],
      builtBy: "Baháʼí Community",
      builtIn: "1986",
      isFavorite: false,
    },

    {
      id: 219,
      name: "Chandigarh Capitol",
      period: "Modern",
      category: "Government Architecture",
      location: "Chandigarh",
      region: "North India",
      image: "https://static.dezeen.com/uploads/2016/08/capitol-complex-le-corbusier-chandigarh-india-benjamin-hosking_dezeen_1568_1.jpg",
      shortDescription: "A modernist government buildings, known for their minimalist design architecute.",
      description:"Chandigarh Capitol Complex is a modern architectural complex designed by Le Corbusier in the 1950s. It houses key government buildings like the High Court, Secretariat, and Legislative Assembly. The complex is a UNESCO World Heritage Site and is renowned for its bold modernist design and urban planning.",
      historicalSignificance: "Designed by Le Corbusier.",
      architecturalFeatures: ["Brutalist design", "Geometric forms"],
      builtBy: "Le Corbusier",
      builtIn: "1950s",
      isFavorite: false,
    },

    {
      id: 220,
      name: "India Gate",
      period: "Modern",
      category: "War Memorial",
      location: "New Delhi",
      region: "North India",
      image: "https://i.pinimg.com/736x/85/54/d4/8554d45ac8bd7f15c9b7e132c93f46e9.jpg",
      shortDescription: "A memorial for Indian soldiers, honoring their bravery and sacrifice.",
      description:"India Gate is a prominent war memorial in New Delhi, built in 1931 to honor Indian soldiers who died during World War I. Designed by Sir Edwin Lutyens, it stands as a symbol of sacrifice and national pride.",
      historicalSignificance: "Symbol of sacrifice.",
      architecturalFeatures: ["Triumphal arch", "Stone construction"],
      builtBy: "Edwin Lutyens",
      builtIn: "1931",
      isFavorite: false,
    },

    {
      id: 221,
      name: "Vidhana Soudha",
      period: "Modern",
      category: "Government Building",
      location: "Bengaluru",
      region: "South India",
      image: "https://i.pinimg.com/1200x/a4/f3/c7/a4f3c773da35bc3b0cb0661eff8b781d.jpg",
      shortDescription: "The seat of Karnataka legislature, known for its distinctive architecture.",
      description:"Vidhana Soudha is the seat of the Karnataka State Legislature in Bengaluru. Completed in 1956, it is renowned for its grand Neo-Dravidian architecture, massive granite structure, and impressive dome, symbolizing the authority and dignity of democratic governance.",
      historicalSignificance: "Blend of Dravidian and modern styles.",
      architecturalFeatures: ["Granite construction", "Dome and pillars"],
      builtBy: "Kengal Hanumanthaiah",
      builtIn: "1956",
      isFavorite: false,
    },

    {
      id: 222,
      name: "Rashtrapati Bhavan",
      period: "Modern",
      category: "Presidential Residence",
      location: "New Delhi",
      region: "North India",
      image: "https://i.pinimg.com/1200x/b1/64/18/b16418fedb969decdc99d3ce942981a3.jpg",
      shortDescription: "The official residence of the President of India, symbolizing authority and grandeur.",
      description:"Rashtrapati Bhavan",
      historicalSignificance: "Symbol of Indian democracy.",
      architecturalFeatures: ["Indo-Saracenic style", "Grand dome"],
      builtBy: "Edwin Lutyens",
      builtIn: "1929",
      isFavorite: false,
    },

    {
      id: 223,
      name: "Jawahar Kala Kendra",
      period: "Modern",
      category: "Cultural Center",
      location: "Jaipur",
      region: "North India",
      image: "https://i.pinimg.com/1200x/bc/8c/ac/bc8cacc09979e4b05fea6936f3805ff8.jpg",
      shortDescription: "An arts and cultural center, showcasing the exhibitions, and creatice activities.",
      description:"Jawahar Kala Kendra",
      historicalSignificance: "Inspired by ancient Vastu principles.",
      architecturalFeatures: ["Navagraha concept", "Modern layout"],
      builtBy: "Charles Correa",
      builtIn: "1992",
      isFavorite: false,
    },

    {
      id: 224,
      name: "Sabarmati Ashram",
      period: "Modern",
      category: "Historical Site",
      location: "Ahmedabad",
      region: "West India",
      image: "https://i.pinimg.com/1200x/1c/c8/c6/1cc8c6186946bd258acdd54f43bcc991.jpg",
      shortDescription: "The residence of Mahatma Gandhi, preserved as a sybmol of his life and legacy.",
      description:"Sabarmati Ashram is a historic ashram in Ahmedabad, established by Mahatma Gandhi in 1917. It served as the center of India’s freedom movement and was the starting point of the famous Dandi March. Today, it stands as a museum and memorial dedicated to Gandhi’s life and teachings.",
      historicalSignificance: "Center of freedom movement.",
      architecturalFeatures: ["Simple structures", "Eco-friendly design"],
      builtBy: "Mahatma Gandhi",
      builtIn: "1917",
      isFavorite: false,
    },
  ],
  reducers:{
    toggleLike : (state, action)=>{
      const id = action.payload;
      const item = state.find((arch)=>arch.id===id)
      if(item){
        item.isFavorite = !item.isFavorite
      }
    }
  }
})

export const {toggleLike} = ArchitectureSlice.actions
export default ArchitectureSlice.reducer