import { createSlice } from "@reduxjs/toolkit";

const ArchitectureSlice = createSlice({
    name:'architectures',
    initialState:[
    {
      id: 201,
      name: "Indus Valley Civilization",
      period: "Ancient",
      category: "Urban Architecture",
      location: "Harappa, Mohenjo-Daro",
      region: "North-West India",
      image: "https://i.pinimg.com/1200x/db/62/dc/db62dc97fd2d413459b10bc1b4260103.jpg",
      description:
        "One of the world’s earliest urban civilizations known for advanced town planning.",
      historicalSignificance:
        "Showcases advanced drainage systems and grid planning.",
      architecturalFeatures: [
        "Grid-based city layout",
        "Advanced drainage system",
        "Brick houses",
      ],
      builtBy: "Indus Valley People",
      builtIn: "2500 BCE",
      isFavorite: false,
    },
    {
      id: 202,
      name: "Sanchi Stupa",
      period: "Ancient",
      category: "Stupa",
      location: "Madhya Pradesh",
      region: "Central India",
      image: "https://i.pinimg.com/1200x/7a/59/f9/7a59f907add61846e694eb6a5fbaef0b.jpg",
      description: "A Buddhist monument commissioned by Emperor Ashoka for worship.",
      historicalSignificance: "One of the oldest stone structures in India.",
      architecturalFeatures: [
        "Hemispherical dome",
        "Toranas (gateways)",
        "Relief carvings",
      ],
      builtBy: "Emperor Ashoka",
      builtIn: "3rd Century BCE",
      isFavorite: false,
    },

    {
      id: 203,
      name: "Ajanta & Ellora Caves",
      period: "Ancient",
      category: "Rock-Cut Architecture",
      location: "Maharashtra",
      region: "Western India",
      image: "https://i.pinimg.com/1200x/c9/01/86/c901868fb22201c991135b17c4fa3085.jpg",
      description: "Ancient rock-cut caves, famous for sculptures and murals, attract visitors from the world.",
      historicalSignificance:
        "Represents Buddhist, Hindu, and Jain traditions.",
      architecturalFeatures: [
        "Rock-cut temples",
        "Wall paintings",
        "Monolithic structures",
      ],
      builtBy: "Various Dynasties",
      builtIn: "2nd Century BCE – 6th Century CE",
      isFavorite: false,
    },

    {
      id: 204,
      name: "Ashokan Pillars",
      period: "Ancient",
      category: "Monument",
      location: "Across India",
      region: "Pan India",
      image: "https://i.pinimg.com/1200x/6c/6a/a3/6c6aa32957af5a054bf624c949153ec5.jpg",
      description: "Stone pillars, intricately carved and erected by Emperor Ashoka.",
      historicalSignificance:
        "Symbol of Mauryan power and Buddhist principles.",
      architecturalFeatures: [
        "Polished sandstone",
        "Lion capital",
        "Edicts inscribed",
      ],
      builtBy: "Emperor Ashoka",
      builtIn: "3rd Century BCE",
      isFavorite: false,
    },

    {
      id: 205,
      name: "Barabar Caves",
      period: "Ancient",
      category: "Cave Architecture",
      location: "Bihar",
      region: "Eastern India",
      image: "https://i.pinimg.com/736x/d7/58/e5/d758e5caacc1b56d686881101dcff2c7.jpg",
      description: "Oldest surviving rock-cut caves in India, known for their historical significance.",
      historicalSignificance: "Dedicated to Ajivika monks.",
      architecturalFeatures: [
        "Highly polished interiors",
        "Simple rectangular chambers",
      ],
      builtBy: "Mauryan Empire",
      builtIn: "3rd Century BCE",
      isFavorite: false,
    },

    {
      id: 206,
      name: "Bhitargaon Temple",
      period: "Ancient",
      category: "Temple",
      location: "Uttar Pradesh",
      region: "North India",
      image: "https://i.pinimg.com/1200x/81/78/bd/8178bdddbf549fff7a8085d0ceb221df.jpg",
      description: "An example of Hindu temple architecture, and showcasing intricate carvings and design.",
      historicalSignificance: "One of the oldest brick temples in India.",
      architecturalFeatures: ["Brick construction", "Shikhara structure"],
      builtBy: "Gupta Dynasty",
      builtIn: "5th Century CE",
      isFavorite: false,
    },

    {
      id: 207,
      name: "Megalithic Structures",
      period: "Ancient",
      category: "Burial Architecture",
      location: "South India",
      region: "Southern India",
      image: "https://cdn.mos.cms.futurecdn.net/XRyDEA6dwNcqJRqbfaBhY.jpg",
      description: "Stone burial monuments from prehistoric times, built to honor the mark sacred spaces.",
      historicalSignificance: "Represents early burial practices.",
      architecturalFeatures: ["Large stone slabs", "Burial chambers"],
      builtBy: "Megalithic Communities",
      builtIn: "1000 BCE",
      isFavorite: false,
    },
    {
      id: 208,
      name: "Qutub Minar",
      period: "Medieval",
      category: "Indo-Islamic Monument",
      location: "Delhi",
      region: "North India",
      image: "https://i.pinimg.com/736x/ff/cd/ed/ffcded3b119ab7d731b689863eb1e49d.jpg",
      description: "Tallest brick minaret in the world, renowned for its architectural brilliance.",
      historicalSignificance: "Symbol of Delhi Sultanate.",
      architecturalFeatures: ["Fluted red sandstone", "Arabic inscriptions"],
      builtBy: "Qutb-ud-din Aibak",
      builtIn: "12th Century",
      isFavorite: false,
    },

    {
      id: 209,
      name: "Jama Masjid",
      period: "Medieval",
      category: "Mosque",
      location: "Delhi",
      region: "North India",
      image: "https://i.pinimg.com/1200x/7b/b7/2f/7bb72ff3616f86428cb65060a1570c90.jpg",
      description: "One of the largest mosques in India, known for its graqnd architecture importance.",
      historicalSignificance: "Mughal architectural masterpiece.",
      architecturalFeatures: ["Large courtyard", "Marble domes"],
      builtBy: "Shah Jahan",
      builtIn: "17th Century",
      isFavorite: false,
    },

    {
      id: 210,
      name: "Gol Gumbaz",
      period: "Medieval",
      category: "Mausoleum",
      location: "Karnataka",
      region: "South India",
      image: "https://i.pinimg.com/1200x/0e/e6/b2/0ee6b2dceb2cd9ea60926c18270a31f7.jpg",
      description: "Famous for its massive and impressive dome, showcasing remarkable architectural skill.",
      historicalSignificance: "Whispering gallery marvel.",
      architecturalFeatures: ["Largest dome in India", "Acoustic design"],
      builtBy: "Adil Shahi Dynasty",
      builtIn: "17th Century",
      isFavorite: false,
    },

    {
      id: 211,
      name: "Charminar",
      period: "Medieval",
      category: "Monument",
      location: "Hyderabad",
      region: "South India",
      image: "https://i.pinimg.com/736x/1a/62/c3/1a62c309f522284076611e89b4288742.jpg",
      description: "An iconic monument with four grand arches, celebrated for its architectural elegance.",
      historicalSignificance: "Symbol of Hyderabad city.",
      architecturalFeatures: ["Four minarets", "Indo-Islamic style"],
      builtBy: "Muhammad Quli Qutb Shah",
      builtIn: "16th Century",
      isFavorite: false,
    },

    {
      id: 212,
      name: "Nagara Style",
      period: "Medieval",
      category: "Temple Architecture Style",
      location: "North India",
      region: "North India",
      image: "https://thearchitectsdiary.com/wp-content/uploads/2023/12/Nagara-style-temple-Image-01-1024x768.webp",
      description: "A distinctive North Indian temple architectural style, with intricate carvings.",
      historicalSignificance: "Distinctive shikhara design.",
      architecturalFeatures: ["Curvilinear towers", "Garbhagriha"],
      builtBy: "Various Dynasties",
      builtIn: "Medieval Period",
      isFavorite: false,
    },

    {
      id: 213,
      name: "Dravidian Style",
      period: "Medieval",
      category: "Temple Architecture Style",
      location: "South India",
      region: "South India",
      image: "https://i.pinimg.com/736x/17/54/dd/1754dde891e3a4ea6fb5f4489821a7c8.jpg",
      description: "A South Indian temple style, known for towering gopurams and intricate carvings.",
      historicalSignificance: "Large gopurams and temple complexes.",
      architecturalFeatures: ["Gopuram towers", "Pillared halls"],
      builtBy: "Chola & Pandya Dynasties",
      builtIn: "Medieval Period",
      isFavorite: false,
    },

    {
      id: 214,
      name: "Vesara Style",
      period: "Medieval",
      category: "Temple Architecture Style",
      location: "Deccan",
      region: "Central India",
      image: "https://pwonlyias.com/wp-content/uploads/2024/04/182-6620b4096a7e8.webp",
      description: "Blend of Nagara and Dravidian styles, known for unique architectural features.",
      historicalSignificance: "Represents architectural fusion.",
      architecturalFeatures: ["Hybrid design", "Ornate carvings"],
      builtBy: "Chalukya Dynasty",
      builtIn: "Medieval Period",
      isFavorite: false,
    },

    {
      id: 215,
      name: "Red Fort",
      period: "Medieval",
      category: "Fort",
      location: "Delhi",
      region: "North India",
      image: "https://i.pinimg.com/736x/42/c5/c1/42c5c1eb9062b5317d303e41d1fc09eb.jpg",
      description: "A massive fort complex built in red sandstone, known for its grand historical importance.",
      historicalSignificance: "Seat of Mughal power.",
      architecturalFeatures: ["Red sandstone walls", "Palace structures"],
      builtBy: "Shah Jahan",
      builtIn: "17th Century",
      isFavorite: false,
    },

    {
      id: 216,
      name: "Amer Fort",
      period: "Medieval",
      category: "Fort",
      location: "Rajasthan",
      region: "North India",
      image: "https://i.pinimg.com/1200x/b2/0b/97/b20b977813320fcb9524cc8d37a3049c.jpg",
      description: "A hilltop fort blending Rajput and Mughal styles, famous for its strategic location.",
      historicalSignificance: "Royal residence of Rajput rulers.",
      architecturalFeatures: ["Mirror work", "Courtyards"],
      builtBy: "Raja Man Singh",
      builtIn: "16th Century",
      isFavorite: false,
    },

    {
      id: 217,
      name: "Hampi Monuments",
      period: "Medieval",
      category: "Temple Complex",
      location: "Karnataka",
      region: "South India",
      image: "https://i.pinimg.com/1200x/36/cf/f0/36cff03f24fabac7b7f9ac8334a0e70d.jpg",
      description: "The ruins of Vijayanagara Empire, showcasing its former grandeur brilliance.",
      historicalSignificance: "UNESCO World Heritage Site.",
      architecturalFeatures: ["Stone temples", "Bazaar streets"],
      builtBy: "Vijayanagara Empire",
      builtIn: "14th Century",
      isFavorite: false,
    },
    {
      id:218,
      name: "Lotus Temple",
      period: "Modern",
      category: "Religious Monument",
      location: "Delhi",
      region: "North India",
      image: "https://i.pinimg.com/1200x/69/2f/e6/692fe6518686fca20d9c134cc9073445.jpg",
      description: "A modern architectural marvel shaped like a lotus, admired for its aesthetic appeal.",
      historicalSignificance: "Symbol of unity and peace.",
      architecturalFeatures: ["Lotus-shaped design", "White marble structure"],
      builtBy: "Baháʼí Community",
      builtIn: "1986",
      isFavorite: false,
    },

    {
      id: 219,
      name: "Chandigarh Capitol",
      period: "Modern",
      category: "Government Architecture",
      location: "Chandigarh",
      region: "North India",
      image: "https://static.dezeen.com/uploads/2016/08/capitol-complex-le-corbusier-chandigarh-india-benjamin-hosking_dezeen_1568_1.jpg",
      description: "A modernist government buildings, known for their minimalist design architecute.",
      historicalSignificance: "Designed by Le Corbusier.",
      architecturalFeatures: ["Brutalist design", "Geometric forms"],
      builtBy: "Le Corbusier",
      builtIn: "1950s",
      isFavorite: false,
    },

    {
      id: 220,
      name: "India Gate",
      period: "Modern",
      category: "War Memorial",
      location: "New Delhi",
      region: "North India",
      image: "https://i.pinimg.com/736x/85/54/d4/8554d45ac8bd7f15c9b7e132c93f46e9.jpg",
      description: "A memorial for Indian soldiers, honoring their bravery and sacrifice.",
      historicalSignificance: "Symbol of sacrifice.",
      architecturalFeatures: ["Triumphal arch", "Stone construction"],
      builtBy: "Edwin Lutyens",
      builtIn: "1931",
      isFavorite: false,
    },

    {
      id: 221,
      name: "Vidhana Soudha",
      period: "Modern",
      category: "Government Building",
      location: "Bengaluru",
      region: "South India",
      image: "https://i.pinimg.com/1200x/a4/f3/c7/a4f3c773da35bc3b0cb0661eff8b781d.jpg",
      description: "The seat of Karnataka legislature, known for its distinctive architecture.",
      historicalSignificance: "Blend of Dravidian and modern styles.",
      architecturalFeatures: ["Granite construction", "Dome and pillars"],
      builtBy: "Kengal Hanumanthaiah",
      builtIn: "1956",
      isFavorite: false,
    },

    {
      id: 222,
      name: "Rashtrapati Bhavan",
      period: "Modern",
      category: "Presidential Residence",
      location: "New Delhi",
      region: "North India",
      image: "https://i.pinimg.com/1200x/b1/64/18/b16418fedb969decdc99d3ce942981a3.jpg",
      description: "The official residence of the President of India, symbolizing authority and grandeur.",
      historicalSignificance: "Symbol of Indian democracy.",
      architecturalFeatures: ["Indo-Saracenic style", "Grand dome"],
      builtBy: "Edwin Lutyens",
      builtIn: "1929",
      isFavorite: false,
    },

    {
      id: 223,
      name: "Jawahar Kala Kendra",
      period: "Modern",
      category: "Cultural Center",
      location: "Jaipur",
      region: "North India",
      image: "https://i.pinimg.com/1200x/bc/8c/ac/bc8cacc09979e4b05fea6936f3805ff8.jpg",
      description: "An arts and cultural center, showcasing the exhibitions, and creatice activities.",
      historicalSignificance: "Inspired by ancient Vastu principles.",
      architecturalFeatures: ["Navagraha concept", "Modern layout"],
      builtBy: "Charles Correa",
      builtIn: "1992",
      isFavorite: false,
    },

    {
      id: 224,
      name: "Sabarmati Ashram",
      period: "Modern",
      category: "Historical Site",
      location: "Ahmedabad",
      region: "West India",
      image: "https://i.pinimg.com/1200x/1c/c8/c6/1cc8c6186946bd258acdd54f43bcc991.jpg",
      description: "The residence of Mahatma Gandhi, preserved as a sybmol of his life and legacy.",
      historicalSignificance: "Center of freedom movement.",
      architecturalFeatures: ["Simple structures", "Eco-friendly design"],
      builtBy: "Mahatma Gandhi",
      builtIn: "1917",
      isFavorite: false,
    },
  ],
  reducers:{
    toggleLike : (state, action)=>{
      const id = action.payload;
      const item = state.find((arch)=>arch.id===id)
      if(item){
        item.isFavorite = !item.isFavorite
      }
    }
  }
})

export const {toggleLike} = ArchitectureSlice.actions
export default ArchitectureSlice.reducer