import {createSlice} from "@reduxjs/toolkit";

const FestivalSlice = createSlice({
    name:"festivals",
    initialState:[
    {
  id: 301,
  name: "Pongal",
  category: "Harvest Festival",
  religion: "Hindu",
  state: "Tamil Nadu",
  month: "January",
  shortDescription:"Pongal is a Tamil harvest festival celebrating gratitude and prosperity.",
  significance: "Thanksgiving to Sun God for a good harvest",
  rituals: "Cooking Pongal rice, Sun worship, cattle decoration",
  highlights: "Kolam designs, Mattu Pongal",
  traditionalFood: "Sweet & Ven Pongal",
  attire: "Traditional silk sarees, veshti",
  image: "https://i.pinimg.com/1200x/17/cb/8c/17cb8c3d6fcb4eff17e71d3e58572d98.jpg",
  isFavorite: false
},
{
  id: 302,
  name: "Makar Sankranti",
  category: "Harvest Festival",
  religion: "Hindu",
  state: "Pan India",
  month: "January",
  shortDescription:"A harvest festival celebrating the Sun’s northward journey and prosperity.",
  significance: "Sun enters Capricorn; marks seasonal change",
  rituals: "Holy bath, kite flying, charity",
  highlights: "Kite festivals",
  traditionalFood: "Til-gud, laddoos",
  attire: "Traditional regional wear",
  image: "https://i.pinimg.com/736x/06/76/05/067605b87260623fa76c30c67a99de67.jpg",
  isFavorite: false
}, 
{
  id: 303,
  name: "Baisakhi",
  category: "Harvest Festival",
  religion: "Sikh",
  state: "Punjab",
  month: "April",
  shortDescription:"A harvest festival marking prosperity and the Sikh New Year.",
  significance: "Harvest celebration & formation of Khalsa",
  rituals: "Gurdwara prayers, Nagar Kirtan",
  highlights: "Bhangra & Gidda",
  traditionalFood: "Langar food",
  attire: "Kurta-pajama, salwar kameez",
  image: "https://i.pinimg.com/736x/5d/61/d5/5d61d529ce609564f3b5d95fec8459b5.jpg",
  isFavorite: false
}, 
{
  id: 304,
  name: "Onam",
  category: "Harvest Festival",
  religion: "Regional",
  state: "Kerala",
  month: "August–September",
  shortDescription:"A harvest festival celebrating unity and Kerala’s cultural heritage.",
  significance: "Welcoming King Mahabali",
  rituals: "Pookalam, snake boat race",
  highlights: "Vallam Kali",
  traditionalFood: "Onam Sadhya",
  attire: "Kasavu saree, mundu",
  image: "https://i.pinimg.com/736x/e4/54/89/e454890fa626cbac9ac13b70ae6107a0.jpg",
  isFavorite: false
}, 
{
  id: 305,
  name: "Lohri",
  category: "Harvest Festival",
  religion: "Hindu",
  state: "Punjab, Haryana",
  month: "January",
  shortDescription:"A winter festival celebrating harvest, warmth, joy and together.",
  significance: "Celebration of winter harvest",
  rituals: "Bonfire, folk songs",
  highlights: "Community dance",
  traditionalFood: "Peanuts, revdi",
  attire: "Woolen traditional wear",
  image: "https://i.pinimg.com/736x/f9/92/36/f99236a2d57f99a7e9a37cae6b70323e.jpg",
  isFavorite: false
},
{
  id: 306,
  name: "Bihu",
  category: "Harvest Festival",
  religion: "Regional",
  state: "Assam",
  month: "April",
  shortDescription:"An Assamese harvest festival celebrating nature and new beginnings.",
  significance: "Assamese New Year & harvest",
  rituals: "Bihu dance, music",
  highlights: "Traditional dance",
  traditionalFood: "Pitha",
  attire: "Mekhela chador",
  image: "https://i.pinimg.com/1200x/c7/62/f0/c762f0b2cd2f6ad1347cb37035cf4127.jpg",
  isFavorite: false
},
{
    id:307,
  name: "Diwali",
  category: "Religious Festival",
  religion: "Hindu",
  state: "Pan India",
  month: "October–November",
  shortDescription:"The festival of lights symbolizing the victory of good over evil.",
  significance: "Victory of light over darkness",
  rituals: "Lakshmi puja, lighting lamps",
  highlights: "Fireworks",
  traditionalFood: "Sweets",
  attire: "Ethnic wear",
  image: "https://i.pinimg.com/736x/0c/fc/15/0cfc15ab116d427764c2f9897a1e4686.jpg",
  isFavorite: false
},
{
  id: 308,
  name: "Holi",
  category: "Religious Festival",
  religion: "Hindu",
  state: "Pan India",
  month: "March",
  shortDescription:"The festival of colors celebrating joy, love, and spring.",
  significance: "Celebrates the victory of good over evil and the arrival of spring",
  rituals: "Holika Dahan, playing with colors, community gatherings",
  highlights: "Color play, music, dance",
  traditionalFood: "Gujiya, thandai",
  attire: "White traditional clothes",
  image: "https://i.pinimg.com/736x/ac/5e/b8/ac5eb84cc8c24781d4fec564fb6459cd.jpg",
  isFavorite: false
},
{
  id: 309,
  name: "Navaratri",
  category: "Religious Festival",
  religion: "Hindu",
  state: "Pan India",
  month: "September–October",
  shortDescription:"A nine-day festival honoring divine feminine energy and devotion.",
  significance: "Honors the nine forms of Goddess Durga",
  rituals: "Fasting, Garba & Dandiya, temple prayers",
  highlights: "Navratri dance festivals",
  traditionalFood: "Fasting foods (sabudana, fruits)",
  attire: "Color-themed traditional attire",
  image: "https://i.pinimg.com/736x/69/66/fa/6966faac2dad15950fee8c30f714bf17.jpg",
  isFavorite: false
},
{
  id: 310,
  name: "Dussehra",
  category: "Religious Festival",
  religion: "Hindu",
  state: "Pan India",
  month: "September–October",
  shortDescription:"A festival celebrating the triumph of good over evil and righteousness.",
  significance: "Celebrates Lord Rama’s victory over Ravana",
  rituals: "Ravana effigy burning, Ram Leela",
  highlights: "Grand processions",
  traditionalFood: "Regional sweets",
  attire: "Traditional ethnic wear",
  image: "https://i.pinimg.com/736x/fd/7f/fd/fd7ffd14e15da42570e99e19c0da2d21.jpg",
  isFavorite: false
},
{
  id: 311,
  name: "Maha Shivaratri",
  category: "Religious Festival",
  religion: "Hindu",
  state: "Pan India",
  month: "February–March",
  shortDescription:"A sacred festival devoted to Lord Shiva and spiritual reflection.",
  significance: "Dedicated to Lord Shiva and spiritual awakening",
  rituals: "Night-long vigil, Shiva lingam abhishekam",
  highlights: "Temple celebrations",
  traditionalFood: "Fruits, milk-based fasting food",
  attire: "Simple traditional clothing",
  image: "https://i.pinimg.com/736x/62/37/56/623756cbab2db8e1317e1cbe76e49144.jpg",
  isFavorite: false
},
{
  id: 312,
  name: "Janmashtami",
  category: "Religious Festival",
  religion: "Hindu",
  state: "Pan India",
  month: "August",
  shortDescription:"The celebration of Lord Krishna’s birth and teachings with devotion.",
  significance: "Celebrates the birth of Lord Krishna",
  rituals: "Midnight prayers, Dahi Handi",
  highlights: "Krishna-Leela enactments",
  traditionalFood: "Butter, sweets",
  attire: "Krishna & Radha costumes",
  image: "https://www.nebulasurgical.com/wp-content/uploads/2024/11/0545-1024x1024.jpg",
  isFavorite: false
},
{
    id:313,
  name: "Eid-ul-Fitr",
  category: "Religious Festival",
  religion: "Muslim",
  state: "Pan India",
  month: "Ramadan end",
  shortDescription:"A festival marking the end of Ramadan with gratitude and sharing.",
  significance: "End of fasting month",
  rituals: "Namaz, charity",
  highlights: "Community feasts",
  traditionalFood: "Sheer Khurma",
  attire: "Traditional Muslim attire",
  image: "https://www.thestatesman.com/wp-content/uploads/2022/05/Eid-at-Jama-Masjid-6-1024x729.jpg",
  isFavorite: false
},
{
    id:314,
  name: "Eid-ul-Adha",
  category: "Religious Festival",
  religion: "Muslim",
  state: "Pan India",
  month: "June–July",
  shortDescription:"A festival symbolizing sacrifice, faith, and devotion to humanity.",
  significance: "Festival of sacrifice",
  rituals: "Qurbani, prayers",
  highlights: "Charity",
  traditionalFood: "Meat dishes",
  attire: "Ethnic wear",
  image: "https://i0.wp.com/kristinareports.net/wp-content/uploads/2024/04/99588495.jpg?resize=400%2C300&ssl=1",
  isFavorite: false
},
{
    id:315,
  name: "Christmas",
  category: "Religious Festival",
  religion: "Christian",
  state: "Pan India",
  month: "December",
  shortDescription:"A festival celebrating the birth of Jesus Christ, love and compassion.",
  significance: "Birth of Jesus Christ",
  rituals: "Church prayers",
  highlights: "Christmas tree, carols",
  traditionalFood: "Plum cake",
  attire: "Festive clothing",
  image: "https://img.freepik.com/premium-photo/merry-christmas-festival-with-santa-claus_1273852-1550.jpg",
  isFavorite: false
},
{
    id:316,
  name: "Easter",
  category: "Religious Festival",
  religion: "Christian",
  state: "Pan India",
  month: "March–April",
  shortDescription:"A Christian festival celebrating resurrection and hope for new life.",
  significance: "Resurrection of Christ",
  rituals: "Church services",
  highlights: "Easter eggs",
  traditionalFood: "Bread & eggs",
  attire: "Formal wear",
  image: "https://cdn.thecollector.com/wp-content/uploads/2024/03/easter-celebrations-christianity.jpg",
  isFavorite: false
},
{
    id:317,
  name: "Guru Nanak Jayanti",
  category: "Religious Festival",
  religion: "Sikh",
  state: "Punjab",
  month: "November",
  shortDescription:"A celebration of Guru Nanak’s birth and teachings of equality and peace.",
  significance: "Birth of Guru Nanak",
  rituals: "Akhand Path, Nagar Kirtan",
  highlights: "Processions",
  traditionalFood: "Langar",
  attire: "Traditional Sikh wear",
  image: "https://img.jagranjosh.com/images/2021/November/18112021/Guru-Nanak-Jayanti-2021-Gurupurab-2021.webp",
  isFavorite: false
},
{
    id:318,
  name: "Durga Puja",
  category: "Cultural Festival",
  religion: "Hindu",
  state: "West Bengal",
  month: "September–October",
  shortDescription:"A festival honoring Goddess Durga’s victory over evil and divine power.",
  significance: "Worship of Goddess Durga",
  rituals: "Pandal hopping, idol immersion",
  highlights: "Artistic pandals",
  traditionalFood: "Bhog",
  attire: "Traditional Bengali wear",
  image: "https://i.pinimg.com/736x/94/5d/5e/945d5e34e16a32fa6aa3de61d82b256e.jpg",
  isFavorite: false
},
{
  id: 319,
  name: "Ganesh Chaturthi",
  category: "Cultural & Regional Festival",
  religion: "Hindu",
  state: "Maharashtra",
  month: "August–September",
  shortDescription:"A festival celebrating the birth of Lord Ganesha with devotion and joy.",
  significance: "Celebrates the birth of Lord Ganesha, the remover of obstacles",
  rituals: "Ganesh idol installation, daily prayers, immersion ceremony (Visarjan)",
  highlights: "Grand public pandals and processions",
  traditionalFood: "Modak",
  attire: "Traditional Maharashtrian attire",
  image: "https://a.storyblok.com/f/95452/4592x3448/dd98301adc/india-mumbai-ganesh-visarjan.jpg/m/1000x1000/filters:focal(2961x1059:2962x1060)",
  isFavorite: false
},
{
  id: 320,
  name: "Ratha Yatra",
  category: "Cultural & Regional Festival",
  religion: "Hindu",
  state: "Odisha",
  month: "June–July",
  shortDescription:"A chariot festival dedicated to Lord Jagannath drawing millions of devotees.",
  significance: "Annual chariot festival of Lord Jagannath",
  rituals: "Pulling the massive chariots",
  highlights: "World-famous temple chariot procession",
  traditionalFood: "Mahaprasad",
  attire: "Traditional Odia clothing",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8nuZnXm-o5IZmMbBiTccqloRVAsYVVsiR1A&s",
  isFavorite: false
},
{
  id: 321,
  name: "Chhath Puja",
  category: "Cultural & Regional Festival",
  religion: "Hindu",
  state: "Bihar",
  month: "October–November",
  shortDescription:"A festival worshipping the Sun God for health prosperity and damilly wellbeing.",
  significance: "Dedicated to the Sun God for prosperity and well-being",
  rituals: "Holy river offerings at sunrise and sunset",
  highlights: "Devotional rituals along riverbanks",
  traditionalFood: "Thekua, fruits",
  attire: "Simple traditional attire",
  image: "https://assets.thehansindia.com/h-upload/2024/11/06/1495072-puja.webp",
  isFavorite: false
},
{
  id: 322,
  name: "Teej",
  category: "Cultural & Regional Festival",
  religion: "Hindu",
  state: "Rajasthan",
  month: "July–August",
  shortDescription:"A festival celebrating marital happiness and devotion among women devotees.",
  significance: "Celebrates marital happiness and monsoon season",
  rituals: "Fasting, swings, prayers",
  highlights: "Colorful folk dances and songs",
  traditionalFood: "Ghewar",
  attire: "Bright traditional Rajasthani dresses",
  image: "https://ik.imagekit.io/x7ulapdbp/82f52af0-caf4-48c5-9f59-b9b1f0308d94-women-in-teej-procession-rajasthan.jpg",
  isFavorite: false
},
{
  id: 323,
  name: "Hornbill Festival",
  category: "Cultural & Regional Festival",
  religion: "Tribal",
  state: "Nagaland",
  month: "December",
  shortDescription:"A cultural festival showcasing Naga traditions and unity through music and dance.",
  significance: "Showcases the culture and traditions of Naga tribes",
  rituals: "Traditional performances and exhibitions",
  highlights: "Tribal dances, crafts, and cuisine",
  traditionalFood: "Naga tribal cuisine",
  attire: "Traditional tribal attire",
  image: "https://thumbs.dreamstime.com/b/hornbill-festival-nagaland-india-kisama-kohima-angami-people-feasting-every-year-st-week-december-great-80928117.jpg",
  isFavorite: false
},
{
    id:324,
  name: "Kumbh Mela",
  category: "Fair",
  religion: "Hindu",
  state: "Prayagraj / Haridwar",
  month: "Varies",
  shortDescription:"A sacred pilgrimage festival centered on spiritual cleansing and religious faith.",
  significance: "Largest spiritual gathering",
  rituals: "Holy river bathing",
  highlights: "Naga sadhus",
  traditionalFood: "Satvik food",
  attire: "Traditional ascetic wear",
  image: "https://media.cnn.com/api/v1/images/stellar/prod/210331234837-03-india-kumbh-mela-2021.jpg?q=w_1600,h_1067,x_0,y_0,c_fill",
  isFavorite: false
},
{
  id: 325,
  name: "Pushkar Camel Fair",
  category: "Fairs & Traditional Celebrations",
  religion: "Cultural",
  state: "Rajasthan",
  month: "November",
  shortDescription:"A vibrant fair celebrating culture, trade, and tradition in Rajasthan annually.",
  significance: "One of the largest camel and livestock fairs in the world",
  rituals: "Camel trading, cultural competitions, folk performances",
  highlights: "Camel races, traditional music and dance",
  traditionalFood: "Rajasthani cuisine",
  attire: "Traditional Rajasthani attire",
  image: "https://media.istockphoto.com/id/618971790/photo/traditional-camel-decoration-competition-camel-mela-in-pushkar.jpg?s=612x612&w=0&k=20&c=k-rvuc1jUjMwk9wDNJF_KUj85skqdAl4J4c7ZP3HNvg=",
  isFavorite: false
},
{
  id: 326,
  name: "Surajkund Mela",
  category: "Fairs & Traditional Celebrations",
  religion: "Cultural",
  state: "Haryana",
  month: "February",
  shortDescription:"A crafts fair showcasing India’s traditional arts from across regions.",
  significance: "International crafts fair promoting traditional arts and handicrafts",
  rituals: "Craft exhibitions, cultural performances",
  highlights: "Handicrafts, folk dances, international participation",
  traditionalFood: "Regional Indian cuisines",
  attire: "Traditional attire from various states",
  image: "https://media.istockphoto.com/id/1163574994/photo/surajkund-international-crafts-mela-crowd-is-enjoying.jpg?s=612x612&w=0&k=20&c=i3JKAkDs1xz8hiOJW3yxAClIEbzn7xxmgeZ5DQ5__WQ=",
  isFavorite: false
},
{
  id: 327,
  name: "Thrissur Pooram",
  category: "Fairs & Traditional Celebrations",
  religion: "Hindu",
  state: "Kerala",
  month: "April–May",
  shortDescription:"A grand temple festival known for elephants and fireworks in kerala state.",
  significance: "A grand temple festival showcasing Kerala’s cultural heritage",
  rituals: "Elephant processions, percussion ensembles",
  highlights: "Decorated elephants, fireworks",
  traditionalFood: "Kerala temple offerings",
  attire: "Traditional Kerala attire",
  image: "https://bharatarticles.com/wp-content/uploads/2025/04/ChatGPT-Image-Apr-15-2025-12_17_13-AM.jpg",
  isFavorite: false
},
{
  id: 328,
  name: "Taj Mahotsav",
  category: "Fairs & Traditional Celebrations",
  religion: "Cultural",
  state: "Uttar Pradesh",
  month: "February",
  shortDescription:"A cultural festival celebrating Indian art and heritage near the Taj Mahal.",
  significance: "Celebrates Indian arts, crafts, and culture near the Taj Mahal",
  rituals: "Cultural performances, craft exhibitions",
  highlights: "Art shows, folk music, dance programs",
  traditionalFood: "North Indian traditional dishes",
  attire: "Ethnic Indian wear",
  image: "https://www.topindianholidays.com/fair_images/taj-mahotsav.webp",
  isFavorite: false
}
  ],
  reducers:{
    toggleLike:(state,action)=>{
      const id=action.payload;
      const item=state.find((fes)=> fes.id===id)
      if(item){
        item.isFavorite=!item.isFavorite
      }
    }
  }
});
export const {toggleLike}=FestivalSlice.actions
export default FestivalSlice.reducer;