import {createSlice} from "@reduxjs/toolkit";

const FestivalSlice = createSlice({
    name:"festivals",
    initialState:[
    {
  id: 301,
  name: "Pongal",
  category: "Harvest Festival",
  religion: "Hindu",
  state: "Tamil Nadu",
  month: "January",
  shortDescription:"Pongal is a Tamil harvest festival celebrating gratitude and prosperity.",
  description:"Pongal is a major harvest festival celebrated mainly in Tamil Nadu during January. It marks thanksgiving to the Sun God for a bountiful harvest and is celebrated over four days with rituals, traditional foods, kolam decorations, and cultural festivities.",
  significance: "Thanksgiving to Sun God for a good harvest",
  rituals: "Cooking Pongal rice, Sun worship, cattle decoration",
  highlights: "Kolam designs, Mattu Pongal",
  traditionalFood: "Sweet & Ven Pongal",
  attire: "Traditional silk sarees, veshti",
  image: "https://i.pinimg.com/1200x/17/cb/8c/17cb8c3d6fcb4eff17e71d3e58572d98.jpg",
  isFavorite: false
},
{
  id: 302,
  name: "Makar Sankranti",
  category: "Harvest Festival",
  religion: "Hindu",
  state: "Pan India",
  month: "January",
  shortDescription:"A harvest festival celebrating the Sun’s northward journey and prosperity.",
  description:"Makar Sankranti is a major Hindu harvest festival celebrated in January, marking the Sun’s transition into the zodiac sign Capricorn (Makara). It signifies the end of the winter solstice and the beginning of longer days. The festival is celebrated with kite flying, holy river baths, donation rituals, and traditional sweets made of sesame and jaggery across different parts of India.",
  significance: "Sun enters Capricorn; marks seasonal change",
  rituals: "Holy bath, kite flying, charity",
  highlights: "Kite festivals",
  traditionalFood: "Til-gud, laddoos",
  attire: "Traditional regional wear",
  image: "https://i.pinimg.com/736x/06/76/05/067605b87260623fa76c30c67a99de67.jpg",
  isFavorite: false
}, 
{
  id: 303,
  name: "Baisakhi",
  category: "Harvest Festival",
  religion: "Sikh",
  state: "Punjab",
  month: "April",
  shortDescription:"A harvest festival marking prosperity and the Sikh New Year.",
  description:"Baisakhi is a vibrant harvest festival celebrated mainly in Punjab in April. It marks the beginning of the Punjabi New Year and commemorates the formation of the Khalsa in 1699 by Guru Gobind Singh. The festival is celebrated with traditional dances like Bhangra and Gidda, community feasts, and visits to Gurdwaras.",
  significance: "Harvest celebration & formation of Khalsa",
  rituals: "Gurdwara prayers, Nagar Kirtan",
  highlights: "Bhangra & Gidda",
  traditionalFood: "Langar food",
  attire: "Kurta-pajama, salwar kameez",
  image: "https://i.pinimg.com/736x/5d/61/d5/5d61d529ce609564f3b5d95fec8459b5.jpg",
  isFavorite: false
}, 
{
  id: 304,
  name: "Onam",
  category: "Harvest Festival",
  religion: "Regional",
  state: "Kerala",
  month: "August–September",
  shortDescription:"A harvest festival celebrating unity and Kerala’s cultural heritage.",
  description:"Onam is a major harvest festival celebrated in Kerala, usually in August or September. It commemorates the homecoming of the legendary King Mahabali and symbolizes prosperity and unity. The festival is marked by floral decorations (Pookalam), traditional feasts (Onasadya), boat races, and cultural performances.",
  significance: "Welcoming King Mahabali",
  rituals: "Pookalam, snake boat race",
  highlights: "Vallam Kali",
  traditionalFood: "Onam Sadhya",
  attire: "Kasavu saree, mundu",
  image: "https://i.pinimg.com/736x/e4/54/89/e454890fa626cbac9ac13b70ae6107a0.jpg",
  isFavorite: false
}, 
{
  id: 305,
  name: "Lohri",
  category: "Harvest Festival",
  religion: "Hindu",
  state: "Punjab, Haryana",
  month: "January",
  shortDescription:"A winter festival celebrating harvest, warmth, joy and together.",
  description:"Lohri is a popular winter harvest festival celebrated mainly in Punjab and North India in January. It marks the end of winter and the harvesting of rabi crops. The festival is celebrated with bonfires, folk songs, dances like Bhangra and Gidda, and offerings of peanuts, jaggery, and popcorn.",
  significance: "Celebration of winter harvest",
  rituals: "Bonfire, folk songs",
  highlights: "Community dance",
  traditionalFood: "Peanuts, revdi",
  attire: "Woolen traditional wear",
  image: "https://i.pinimg.com/736x/f9/92/36/f99236a2d57f99a7e9a37cae6b70323e.jpg",
  isFavorite: false
},
{
  id: 306,
  name: "Bihu",
  category: "Harvest Festival",
  religion: "Regional",
  state: "Assam",
  month: "April",
  shortDescription:"An Assamese harvest festival celebrating nature and new beginnings.",
  description:"Bihu is a major festival of Assam, celebrated to mark the Assamese New Year and the agricultural cycle. It is observed in three forms—Rongali Bihu (spring), Kongali Bihu (autumn), and Bhogali Bihu (harvest). The festival is known for traditional Bihu dance, folk music, community feasts, and celebrations connected to farming and nature.",
  significance: "Assamese New Year & harvest",
  rituals: "Bihu dance, music",
  highlights: "Traditional dance",
  traditionalFood: "Pitha",
  attire: "Mekhela chador",
  image: "https://i.pinimg.com/1200x/c7/62/f0/c762f0b2cd2f6ad1347cb37035cf4127.jpg",
  isFavorite: false
},
{
    id:307,
  name: "Diwali",
  category: "Religious Festival",
  religion: "Hindu",
  state: "Pan India",
  month: "October–November",
  shortDescription:"The festival of lights symbolizing the victory of good over evil.",
  description:"Diwali is a major Hindu festival of lights celebrated across India, usually in October or November. It symbolizes the victory of light over darkness and good over evil, and commemorates the return of Lord Rama to Ayodhya. The festival is marked by lighting diyas, decorating homes with rangoli, bursting fireworks, exchanging sweets, and performing Lakshmi Puja.",
  significance: "Victory of light over darkness",
  rituals: "Lakshmi puja, lighting lamps",
  highlights: "Fireworks",
  traditionalFood: "Sweets",
  attire: "Ethnic wear",
  image: "https://i.pinimg.com/736x/0c/fc/15/0cfc15ab116d427764c2f9897a1e4686.jpg",
  isFavorite: false
},
{
  id: 308,
  name: "Holi",
  category: "Religious Festival",
  religion: "Hindu",
  state: "Pan India",
  month: "March",
  shortDescription:"The festival of colors celebrating joy, love, and spring.",
  description:"Holi is a vibrant Hindu festival of colors celebrated in March across India. It marks the arrival of spring and symbolizes the victory of good over evil. The festival is celebrated with colorful powders, music, dance, bonfires (Holika Dahan), and sharing sweets, spreading joy and unity.",
  significance: "Celebrates the victory of good over evil and the arrival of spring",
  rituals: "Holika Dahan, playing with colors, community gatherings",
  highlights: "Color play, music, dance",
  traditionalFood: "Gujiya, thandai",
  attire: "White traditional clothes",
  image: "https://i.pinimg.com/736x/ac/5e/b8/ac5eb84cc8c24781d4fec564fb6459cd.jpg",
  isFavorite: false
},
{
  id: 309,
  name: "Navaratri",
  category: "Religious Festival",
  religion: "Hindu",
  state: "Pan India",
  month: "September–October",
  shortDescription:"A nine-day festival honoring divine feminine energy and devotion.",
  description:"Navaratri is a major Hindu festival celebrated over nine nights, usually in September or October, in honor of Goddess Durga and her nine forms. It symbolizes the triumph of good over evil and is marked by fasting, prayers, devotional music, and vibrant dances like Garba and Dandiya in different parts of India.",
  significance: "Honors the nine forms of Goddess Durga",
  rituals: "Fasting, Garba & Dandiya, temple prayers",
  highlights: "Navratri dance festivals",
  traditionalFood: "Fasting foods (sabudana, fruits)",
  attire: "Color-themed traditional attire",
  image: "https://i.pinimg.com/736x/69/66/fa/6966faac2dad15950fee8c30f714bf17.jpg",
  isFavorite: false
},
{
  id: 310,
  name: "Dussehra",
  category: "Religious Festival",
  religion: "Hindu",
  state: "Pan India",
  month: "September–October",
  shortDescription:"A festival celebrating the triumph of good over evil and righteousness.",
  description:"Dussehra (also known as Vijayadashami) is a major Hindu festival celebrated in September or October. It marks the victory of Lord Rama over Ravana and symbolizes the triumph of good over evil. The festival is observed with Ramleela performances, burning of Ravana effigies, and grand processions in many parts of India.",
  significance: "Celebrates Lord Rama’s victory over Ravana",
  rituals: "Ravana effigy burning, Ram Leela",
  highlights: "Grand processions",
  traditionalFood: "Regional sweets",
  attire: "Traditional ethnic wear",
  image: "https://i.pinimg.com/736x/fd/7f/fd/fd7ffd14e15da42570e99e19c0da2d21.jpg",
  isFavorite: false
},
{
  id: 311,
  name: "Maha Shivaratri",
  category: "Religious Festival",
  religion: "Hindu",
  state: "Pan India",
  month: "February–March",
  shortDescription:"A sacred festival devoted to Lord Shiva and spiritual reflection.",
  description:"Maha Shivaratri is a major Hindu festival dedicated to Lord Shiva, celebrated in February or March. It marks the divine marriage of Shiva and Parvati and symbolizes spiritual awakening and devotion. Devotees observe fasting, night-long prayers, chanting of “Om Namah Shivaya,” and offer milk and bilva leaves to Shiva Lingam.",
  significance: "Dedicated to Lord Shiva and spiritual awakening",
  rituals: "Night-long vigil, Shiva lingam abhishekam",
  highlights: "Temple celebrations",
  traditionalFood: "Fruits, milk-based fasting food",
  attire: "Simple traditional clothing",
  image: "https://i.pinimg.com/736x/62/37/56/623756cbab2db8e1317e1cbe76e49144.jpg",
  isFavorite: false
},
{
  id: 312,
  name: "Janmashtami",
  category: "Religious Festival",
  religion: "Hindu",
  state: "Pan India",
  month: "August",
  shortDescription:"The celebration of Lord Krishna’s birth and teachings with devotion.",
  description:"Janmashtami is a Hindu festival celebrating the birth of Lord Krishna, observed in August or September. It symbolizes divine love and righteousness and is marked by fasting, devotional singing, midnight prayers, reenactments of Krishna’s life, and the breaking of curd pots (Dahi Handi) in many regions.",
  significance: "Celebrates the birth of Lord Krishna",
  rituals: "Midnight prayers, Dahi Handi",
  highlights: "Krishna-Leela enactments",
  traditionalFood: "Butter, sweets",
  attire: "Krishna & Radha costumes",
  image: "https://www.nebulasurgical.com/wp-content/uploads/2024/11/0545-1024x1024.jpg",
  isFavorite: false
},
{
    id:313,
  name: "Eid-ul-Fitr",
  category: "Religious Festival",
  religion: "Muslim",
  state: "Pan India",
  month: "Ramadan end",
  shortDescription:"A festival marking the end of Ramadan with gratitude and sharing.",
  description:"Eid-ul-Fitr is an important Islamic festival marking the end of the holy month of Ramadan. It is celebrated with special prayers at mosques, charity (Zakat al-Fitr), festive meals, and gatherings with family and friends. The festival symbolizes gratitude, compassion, and unity within the Muslim community.",
  significance: "End of fasting month",
  rituals: "Namaz, charity",
  highlights: "Community feasts",
  traditionalFood: "Sheer Khurma",
  attire: "Traditional Muslim attire",
  image: "https://www.thestatesman.com/wp-content/uploads/2022/05/Eid-at-Jama-Masjid-6-1024x729.jpg",
  isFavorite: false
},
{
    id:314,
  name: "Eid-ul-Adha",
  category: "Religious Festival",
  religion: "Muslim",
  state: "Pan India",
  month: "June–July",
  shortDescription:"A festival symbolizing sacrifice, faith, and devotion to humanity.",
  description:"Eid-ul-Adha is a significant Islamic festival that commemorates Prophet Ibrahim’s devotion and willingness to sacrifice his son in obedience to God. Celebrated about two months after Eid-ul-Fitr, it involves special prayers, the ritual sacrifice of an animal (Qurbani), and sharing the meat with family, friends, and the needy. The festival symbolizes faith, obedience, and charity.",
  significance: "Festival of sacrifice",
  rituals: "Qurbani, prayers",
  highlights: "Charity",
  traditionalFood: "Meat dishes",
  attire: "Ethnic wear",
  image: "https://i0.wp.com/kristinareports.net/wp-content/uploads/2024/04/99588495.jpg?resize=400%2C300&ssl=1",
  isFavorite: false
},
{
    id:315,
  name: "Christmas",
  category: "Religious Festival",
  religion: "Christian",
  state: "Pan India",
  month: "December",
  shortDescription:"A festival celebrating the birth of Jesus Christ, love and compassion.",
  description:"Christmas is a Christian festival celebrated on December 25th to commemorate the birth of Jesus Christ. It is marked by church services, festive decorations, exchanging gifts, singing carols, and family gatherings. The festival symbolizes joy, love, and hope.",
  significance: "Birth of Jesus Christ",
  rituals: "Church prayers",
  highlights: "Christmas tree, carols",
  traditionalFood: "Plum cake",
  attire: "Festive clothing",
  image: "https://img.freepik.com/premium-photo/merry-christmas-festival-with-santa-claus_1273852-1550.jpg",
  isFavorite: false
},
{
    id:316,
  name: "Easter",
  category: "Religious Festival",
  religion: "Christian",
  state: "Pan India",
  month: "March–April",
  shortDescription:"A Christian festival celebrating resurrection and hope for new life.",
  description:"Easter is a major Christian festival celebrating the resurrection of Jesus Christ from the dead, observed on a Sunday between March and April. It symbolizes victory over sin and death, renewal, and hope. The festival is marked by church services, prayers, festive meals, and customs like Easter eggs and egg hunts.",
  significance: "Resurrection of Christ",
  rituals: "Church services",
  highlights: "Easter eggs",
  traditionalFood: "Bread & eggs",
  attire: "Formal wear",
  image: "https://cdn.thecollector.com/wp-content/uploads/2024/03/easter-celebrations-christianity.jpg",
  isFavorite: false
},
{
    id:317,
  name: "Guru Nanak Jayanti",
  category: "Religious Festival",
  religion: "Sikh",
  state: "Punjab",
  month: "November",
  shortDescription:"A celebration of Guru Nanak’s birth and teachings of equality and peace.",
  description:"Guru Nanak Jayanti is a Sikh festival celebrating the birth of Guru Nanak Dev Ji, the founder of Sikhism. Observed in November, it is marked by prayers, singing of hymns (kirtan), processions (Nagar Kirtan), and community meals (Langar) in Gurdwaras, emphasizing devotion, equality, and service to humanity.",
  significance: "Birth of Guru Nanak",
  rituals: "Akhand Path, Nagar Kirtan",
  highlights: "Processions",
  traditionalFood: "Langar",
  attire: "Traditional Sikh wear",
  image: "https://img.jagranjosh.com/images/2021/November/18112021/Guru-Nanak-Jayanti-2021-Gurupurab-2021.webp",
  isFavorite: false
},
{
    id:318,
  name: "Durga Puja",
  category: "Cultural Festival",
  religion: "Hindu",
  state: "West Bengal",
  month: "September–October",
  shortDescription:"A festival honoring Goddess Durga’s victory over evil and divine power.",
  description:"Durga Puja is a major Hindu festival celebrated primarily in West Bengal, Odisha, Assam, and other parts of India, usually in September or October. It honors Goddess Durga’s victory over the demon Mahishasura and symbolizes the triumph of good over evil. The festival features beautifully decorated idols, elaborate pandals, traditional rituals, cultural performances, and community feasts.",
  significance: "Worship of Goddess Durga",
  rituals: "Pandal hopping, idol immersion",
  highlights: "Artistic pandals",
  traditionalFood: "Bhog",
  attire: "Traditional Bengali wear",
  image: "https://i.pinimg.com/736x/94/5d/5e/945d5e34e16a32fa6aa3de61d82b256e.jpg",
  isFavorite: false
},
{
  id: 319,
  name: "Ganesh Chaturthi",
  category: "Cultural & Regional Festival",
  religion: "Hindu",
  state: "Maharashtra",
  month: "August–September",
  shortDescription:"A festival celebrating the birth of Lord Ganesha with devotion and joy.",
  description:"Ganesh Chaturthi is a Hindu festival celebrating the birth of Lord Ganesha, the elephant-headed god of wisdom and prosperity. Observed in August or September, it is marked by installing clay idols of Ganesha in homes and public pandals, performing prayers and aartis, singing devotional songs, and immersing the idols in water (Visarjan) at the end of the festival.",
  significance: "Celebrates the birth of Lord Ganesha, the remover of obstacles",
  rituals: "Ganesh idol installation, daily prayers, immersion ceremony (Visarjan)",
  highlights: "Grand public pandals and processions",
  traditionalFood: "Modak",
  attire: "Traditional Maharashtrian attire",
  image: "https://a.storyblok.com/f/95452/4592x3448/dd98301adc/india-mumbai-ganesh-visarjan.jpg/m/1000x1000/filters:focal(2961x1059:2962x1060)",
  isFavorite: false
},
{
  id: 320,
  name: "Ratha Yatra",
  category: "Cultural & Regional Festival",
  religion: "Hindu",
  state: "Odisha",
  month: "June–July",
  shortDescription:"A chariot festival dedicated to Lord Jagannath drawing millions of devotees.",
  description:"Ratha Yatra is a Hindu festival celebrated mainly in Puri, Odisha, honoring Lord Jagannath, along with his siblings Balabhadra and Subhadra. It involves grand processions where the deities are placed on elaborately decorated chariots and pulled through the streets by devotees. The festival symbolizes devotion, unity, and the journey of life.",
  significance: "Annual chariot festival of Lord Jagannath",
  rituals: "Pulling the massive chariots",
  highlights: "World-famous temple chariot procession",
  traditionalFood: "Mahaprasad",
  attire: "Traditional Odia clothing",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8nuZnXm-o5IZmMbBiTccqloRVAsYVVsiR1A&s",
  isFavorite: false
},
{
  id: 321,
  name: "Chhath Puja",
  category: "Cultural & Regional Festival",
  religion: "Hindu",
  state: "Bihar",
  month: "October–November",
  shortDescription:"A festival worshipping the Sun God for health prosperity and damilly wellbeing.",
  description:"Chhath Puja is a Hindu festival dedicated to the Sun God (Surya) and his wife Usha, primarily celebrated in Bihar, Jharkhand, Uttar Pradesh, and Nepal. Observed over four days, it involves rituals like holy bathing, fasting, and offering prayers to the rising and setting sun, symbolizing gratitude, purification, and devotion.",
  significance: "Dedicated to the Sun God for prosperity and well-being",
  rituals: "Holy river offerings at sunrise and sunset",
  highlights: "Devotional rituals along riverbanks",
  traditionalFood: "Thekua, fruits",
  attire: "Simple traditional attire",
  image: "https://assets.thehansindia.com/h-upload/2024/11/06/1495072-puja.webp",
  isFavorite: false
},
{
  id: 322,
  name: "Teej",
  category: "Cultural & Regional Festival",
  religion: "Hindu",
  state: "Rajasthan",
  month: "July–August",
  shortDescription:"A festival celebrating marital happiness and devotion among women devotees.",
  description:"Teej is a Hindu festival celebrated mainly by women in North India, especially in Rajasthan, Uttar Pradesh, and Bihar. Observed during the monsoon season (July–August), it honors Goddess Parvati and her union with Lord Shiva. The festival is marked by fasting, swinging on decorated swings, singing folk songs, and wearing vibrant traditional attire, symbolizing marital bliss, devotion, and the arrival of the monsoon.",
  significance: "Celebrates marital happiness and monsoon season",
  rituals: "Fasting, swings, prayers",
  highlights: "Colorful folk dances and songs",
  traditionalFood: "Ghewar",
  attire: "Bright traditional Rajasthani dresses",
  image: "https://ik.imagekit.io/x7ulapdbp/82f52af0-caf4-48c5-9f59-b9b1f0308d94-women-in-teej-procession-rajasthan.jpg",
  isFavorite: false
},
{
  id: 323,
  name: "Hornbill Festival",
  category: "Cultural & Regional Festival",
  religion: "Tribal",
  state: "Nagaland",
  month: "December",
  shortDescription:"A cultural festival showcasing Naga traditions and unity through music and dance.",
  description:"Hornbill Festival is an annual cultural festival held in Nagaland every December. It showcases the rich heritage of the Naga tribes through traditional music, dance, crafts, indigenous sports, and food, earning it the nickname “Festival of Festivals” in Northeast India.",
  significance: "Showcases the culture and traditions of Naga tribes",
  rituals: "Traditional performances and exhibitions",
  highlights: "Tribal dances, crafts, and cuisine",
  traditionalFood: "Naga tribal cuisine",
  attire: "Traditional tribal attire",
  image: "https://thumbs.dreamstime.com/b/hornbill-festival-nagaland-india-kisama-kohima-angami-people-feasting-every-year-st-week-december-great-80928117.jpg",
  isFavorite: false
},
{
    id:324,
  name: "Kumbh Mela",
  category: "Fair",
  religion: "Hindu",
  state: "Prayagraj / Haridwar",
  month: "Varies",
  shortDescription:"A sacred pilgrimage festival centered on spiritual cleansing and religious faith.",
  description:"Kumbh Mela is a major Hindu pilgrimage and festival held every 12 years at four sacred river locations in India: Prayagraj, Haridwar, Nashik, and Ujjain. Millions of devotees gather to take a holy dip in the rivers, believing it cleanses sins and grants spiritual merit. The festival also features religious discourses, rituals, and cultural events.",
  significance: "Largest spiritual gathering",
  rituals: "Holy river bathing",
  highlights: "Naga sadhus",
  traditionalFood: "Satvik food",
  attire: "Traditional ascetic wear",
  image: "https://media.cnn.com/api/v1/images/stellar/prod/210331234837-03-india-kumbh-mela-2021.jpg?q=w_1600,h_1067,x_0,y_0,c_fill",
  isFavorite: false
},
{
  id: 325,
  name: "Pushkar Camel Fair",
  category: "Fairs & Traditional Celebrations",
  religion: "Cultural",
  state: "Rajasthan",
  month: "November",
  shortDescription:"A vibrant fair celebrating culture, trade, and tradition in Rajasthan annually.",
  description:"Pushkar Camel Fair is an annual livestock and cultural festival held in Pushkar, Rajasthan, usually in November. It features trading of camels and other animals, traditional music and dance, competitions, fairs, and vibrant cultural activities, attracting tourists and traders from across India and abroad.",
  significance: "One of the largest camel and livestock fairs in the world",
  rituals: "Camel trading, cultural competitions, folk performances",
  highlights: "Camel races, traditional music and dance",
  traditionalFood: "Rajasthani cuisine",
  attire: "Traditional Rajasthani attire",
  image: "https://media.istockphoto.com/id/618971790/photo/traditional-camel-decoration-competition-camel-mela-in-pushkar.jpg?s=612x612&w=0&k=20&c=k-rvuc1jUjMwk9wDNJF_KUj85skqdAl4J4c7ZP3HNvg=",
  isFavorite: false
},
{
  id: 326,
  name: "Surajkund Mela",
  category: "Fairs & Traditional Celebrations",
  religion: "Cultural",
  state: "Haryana",
  month: "February",
  shortDescription:"A crafts fair showcasing India’s traditional arts from across regions.",
  description:"Surajkund Mela is an annual cultural fair held in Surajkund, Haryana, usually in February. It showcases India’s rich handicrafts, handlooms, folk arts, and cuisine from different states, along with cultural performances, making it a vibrant celebration of traditional Indian heritage.",
  significance: "International crafts fair promoting traditional arts and handicrafts",
  rituals: "Craft exhibitions, cultural performances",
  highlights: "Handicrafts, folk dances, international participation",
  traditionalFood: "Regional Indian cuisines",
  attire: "Traditional attire from various states",
  image: "https://media.istockphoto.com/id/1163574994/photo/surajkund-international-crafts-mela-crowd-is-enjoying.jpg?s=612x612&w=0&k=20&c=i3JKAkDs1xz8hiOJW3yxAClIEbzn7xxmgeZ5DQ5__WQ=",
  isFavorite: false
},
{
  id: 327,
  name: "Thrissur Pooram",
  category: "Fairs & Traditional Celebrations",
  religion: "Hindu",
  state: "Kerala",
  month: "April–May",
  shortDescription:"A grand temple festival known for elephants and fireworks in kerala state.",
  description:"Thrissur Pooram is a grand Hindu temple festival celebrated in Thrissur, Kerala, usually in April or May. It is famous for its spectacular procession of decorated elephants, traditional percussion music (Chenda Melam), fireworks, and vibrant cultural displays, honoring Lord Shiva and the local deities.",
  significance: "A grand temple festival showcasing Kerala’s cultural heritage",
  rituals: "Elephant processions, percussion ensembles",
  highlights: "Decorated elephants, fireworks",
  traditionalFood: "Kerala temple offerings",
  attire: "Traditional Kerala attire",
  image: "https://bharatarticles.com/wp-content/uploads/2025/04/ChatGPT-Image-Apr-15-2025-12_17_13-AM.jpg",
  isFavorite: false
},
{
  id: 328,
  name: "Taj Mahotsav",
  category: "Fairs & Traditional Celebrations",
  religion: "Cultural",
  state: "Uttar Pradesh",
  month: "February",
  shortDescription:"A cultural festival celebrating Indian art and heritage near the Taj Mahal.",
  description:"Taj Mahotsav is an annual 10-day cultural festival held in Agra, typically in February. It celebrates India’s rich arts, crafts, cuisine, music, and dance, offering exhibitions, performances, and workshops near the iconic Taj Mahal, attracting both domestic and international tourists.",
  significance: "Celebrates Indian arts, crafts, and culture near the Taj Mahal",
  rituals: "Cultural performances, craft exhibitions",
  highlights: "Art shows, folk music, dance programs",
  traditionalFood: "North Indian traditional dishes",
  attire: "Ethnic Indian wear",
  image: "https://www.topindianholidays.com/fair_images/taj-mahotsav.webp",
  isFavorite: false
}
  ],
  reducers:{
    toggleLike:(state,action)=>{
      const id=action.payload;
      const item=state.find((fes)=> fes.id===id)
      if(item){
        item.isFavorite=!item.isFavorite
      }
    }
  }
});
export const {toggleLike}=FestivalSlice.actions
export default FestivalSlice.reducer;