import { createSlice } from "@reduxjs/toolkit";

const HandicraftSlice = createSlice({
    name:'handicrafts',
    initialState:[
    {
  id: 401,
  name: "Banarasi Silk Sarees",
  category: "Textiles & Fabrics",
  state: "Uttar Pradesh",
  shortDescription:"Banarasi Silk Sarees are handwoven from rich silk, known for intricate gold and silver zari work.",
  significance: "Luxurious silk sarees known for gold and silver brocade work",
  materials: ["Silk",
  "Zari threads"],
  techniques: "Handloom weaving with intricate motifs",
  usage: "Wedding and festive wear",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwSQaa6p_dwftwOCQEEjHTP5fM_3g9vEcZOQ&s",
  isFavorite: false
},
{
  id: 402,
  name: "Kanchipuram Silk",
  category: "Textiles & Fabrics",
  state: "Tamil Nadu",
  shortDescription:"Kanchipuram Silk Sarees are handwoven from pure silk, known for their rich colors and zari work.",
  significance: "Traditional silk sarees with temple-inspired designs",
  materials: ["Pure mulberry silk",
  "Zari"],
  techniques: "Interlocked weaving technique",
  usage: "Bridal and ceremonial wear",
  image: "https://www.deepam.com/cdn/shop/articles/D216968_1080x_8d6419f4-9e6a-4f99-8a9b-c76bdc4bbe54.webp?v=1707470495",
  isFavorite: false
},
{
  id: 403,
  name: "Pashmina Shawls",
  category: "Textiles & Fabrics",
  state: "Jammu & Kashmir",
  shortDescription:"Pashmina Shawls are soft, luxurious shawls from Kashmir, made from fine wool and for their warmth and elegance.",
  significance: "Fine wool shawls known for softness and warmth",
  materials: ["Pashmina wool"],
  techniques: "Hand-spinning and hand-weaving",
  usage: "Luxury winter wear",
  image: "https://sairasboutique.net/cdn/shop/products/DSC_7253-1_1024x1024.jpg?v=1548911649",
  isFavorite: false
},
{
  id: 404,
  name: "Chikankari Embroidery",
  category: "Textiles & Fabrics",
  state: "Uttar Pradesh",
  shortDescription:"Chikankari Embroidery is a delicate hand embroidery from Lucknow, known for its elegant floral patterns on fine fabrics.",
  significance: "Delicate hand embroidery style from Lucknow",
  materials: ["Cotton", "Silk threads"],
  techniques: "Hand embroidery",
  usage: "Traditional garments",
  image: "https://i.pinimg.com/736x/fa/9f/5b/fa9f5b472f4a45b0d6830bf8e4bcb705.jpg",
  isFavorite: false
},
{
  id: 405,
  name: "Ikat Weaving",
  category: "Textiles & Fabrics",
  state: "Odisha / Telangana",
  shortDescription:"Ikat Weaving is a traditional textile art known for its bold patterns created by resist-dyeing yarns before weaving.",
  significance: "Resist-dyeing textile technique with blurred patterns",
  materials: ["Cotton", "Silk"],
  techniques: "Yarn resist dyeing",
  usage: "Sarees, fabrics",
  image: "https://mavuris.com/cdn/shop/articles/ikat_saree_83cc090c-26a0-419d-94e2-5714120070f1.jpg?v=1750319188",
  isFavorite: false
},
{
  id: 406,
  name: "Kalamkari Fabric",
  category: "Textiles & Fabrics",
  state: "Andhra Pradesh",
  shortDescription:"Kalamkari Fabric is a hand-painted or block-printed textile known for its natural dyes and mythological motifs.",
  significance: "Hand-painted or block-printed textile art",
  materials: ["Cotton", "Natural dyes"],
  techniques: "Freehand drawing with pen",
  usage: "Wall hangings, garments",
  image: "https://www.vemshala.com/cdn/shop/files/natural-multi-floral-gold-pen-kalamkari-tussar-silk-saree-141759.jpg?v=1739427746",
  isFavorite: false
},
{
  id: 407,
  name: "Phulkari Embroidery",
  category: "Textiles & Fabrics",
  state: "Punjab",
  shortDescription:"Phulkari Embroidery is a vibrant Punjabi folk art known for its colorful geometric floral patterns stitched on fabric.",
  significance: "Vibrant floral embroidery tradition",
  materials: ["Cotton fabric", "Silk thread"],
  techniques: "Darning stitch embroidery",
  usage: "Dupattas and shawls",
  image: "https://i.pinimg.com/736x/25/da/26/25da26aca2f7b0bedccac0bc7644cfa2.jpg",
  isFavorite: false
},
{
  id: 408,
  name: "Blue Pottery",
  category: "Pottery & Clay Crafts",
  state: "Rajasthan",
  shortDescription:"Blue Pottery is a traditional ceramic art known for its blue-and-white floral designs and delicate craftsmanship.",
  significance: "Distinctive blue-glazed pottery",
  materials: ["Quartz", "Glass", "Multani Mitti"],
  techniques: "Glazing and low-temperature firing",
  usage: "Decorative items",
  image: "https://c9admin.cottage9.com/uploads/2322/image_2023_01_20T09_08_11_450Z-1024x723.png",
  isFavorite: false
},
{
  id: 409,
  name: "Terracotta Art",
  category: "Pottery & Clay Crafts",
  state: "West Bengal",
  shortDescription:"Terracotta Art is a traditional clay craft known for its earthy tones and handcrafted figurines, pots, and decor.",
  significance: "Ancient clay craft used in temples and décor",
  materials: ["Natural clay"],
  techniques: "Hand molding and firing",
  usage: "Sculptures and tiles",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVvs3JvRrPBRMYuTz-QEgs_sGKW-UQj424eA&s",
  isFavorite: false
},
{
  id: 410,
  name: "Molela Clay Work",
  category: "Pottery & Clay Crafts",
  state: "Rajasthan",
  shortDescription:"Molela Clay Work is a traditional Rajasthan craft featuring handcrafted clay plaques of folk motifs.",
  significance: "Raised clay relief work depicting folk deities",
  materials: ["Clay"],
  techniques: "Relief molding",
  usage: "Shrines and wall décor",
  image: "https://i.pinimg.com/736x/80/4e/ff/804eff453406ef035d2b51e7ab4a0286.jpg",
  isFavorite: false
},
{
  id: 411,
  name: "Black Pottery",
  category: "Pottery & Clay Crafts",
  state: "Manipur",
  shortDescription:"Black Pottery is a traditional craft known for its smooth black finish and simple, elegant designs.",
  significance: "Smoky black-finished traditional pottery",
  materials: ["Clay"],
  techniques: "Smoke firing",
  usage: "Utensils and décor",
  image: "https://divya.lovestoblog.com/wp-content/uploads/2024/08/web10-1.png",
  isFavorite: false
},
{
  id: 412,
  name: "Khurja Pottery",
  category: "Pottery & Clay Crafts",
  state: "Uttar Pradesh",
  shortDescription:"Khurja Pottery is a traditional ceramic craft known for its colorful glazes and hand-painted designs.",
  significance: "Famous for glazed ceramic pottery",
  materials: ["Clay"],
  techniques: "Wheel throwing and glazing",
  usage: "Tableware and décor",
  image: "https://i.pinimg.com/1200x/32/cc/51/32cc51eb06203ef1df6bc43338ef62b6.jpg",
  isFavorite: false
},
{
  id: 413,
  name: "Sandalwood Carving",
  category: "Wood & Bamboo Crafts",
  state: "Karnataka",
  shortDescription:"Sandalwood Carving is a traditional craft known for its natural fragrance, and intricate designs.",
  significance: "Fine carving on fragrant sandalwood",
  materials: ["Sandalwood"],
  techniques: "Hand carving",
  usage: "Statues and artifacts",
  image: "https://www.maljiarts.in/cdn/shop/files/IMG_2810.heic?v=1748521779&width=1946",
  isFavorite: false
},
{
  id: 414,
  name: "Rosewood Inlay",
  category: "Wood & Bamboo Crafts",
  state: "Kerala",
  shortDescription:"Rosewood Inlay is a traditional craft featuring intricate inlaid patterns on polished rosewood surfaces.",
  significance: "Decorative wooden inlay craft",
  materials: ["Rosewood", "ivory substitutes"],
  techniques: "Inlay work",
  usage: "Furniture and décor",
  image: "https://upload.wikimedia.org/wikipedia/commons/2/2b/Wood_inlay_Mysore.jpg",
  isFavorite: false
},
{
  id: 415,
  name: "Bamboo Craft",
  category: "Wood & Bamboo Crafts",
  state: "North East India",
  shortDescription:"Bamboo Craft is a traditional art using bamboo to create eco-friendly baskets, decor, and utility items.",
  significance: "Eco-friendly traditional bamboo items",
  materials: ["Bamboo"],
  techniques: "Weaving and binding",
  usage: "Household items",
  image: "https://5.imimg.com/data5/IH/OU/MY-12266299/bamboo-work-handicraft.jpg",
  isFavorite: false
},
{
  id: 416,
  name: "Saharanpur Woodcraft",
  category: "Wood & Bamboo Crafts",
  state: "Uttar Pradesh",
  shortDescription:"Saharanpur Wood Carving is a traditional craft known for its intricate floral and geometric designs carved in wood.",
  significance: "Detailed floral wood carving",
  materials: ["Sheesham wood"],
  techniques: "Hand carving",
  usage: "Furniture and décor",
  image: "https://aarsunwoods.com/wp-content/uploads/2017/09/Pooja-Cabinet-Wood-Temple-in-Teak-Wood-UH-YT-145.jpg",
  isFavorite: false
},
{
  id: 417,
  name: "Channapatna Toys",
  category: "Wood & Bamboo Crafts",
  state: "Karnataka",
  shortDescription:"Channapatna Toys are traditional wooden toys known for their bright colors, smooth finish, and lac coating.",
  significance: "Colorful eco-friendly wooden toys",
  materials: ["Softwood", "natural dyes"],
  techniques: "Lac-turning",
  usage: "Toys and décor",
  image: "https://storeassets.im-cdn.com/media-manager/channapatnatoysin/280eU8ASIK3BTw3yHkER_channapatna%20toys%20banner%2015_621x375_webp.jpg",
  isFavorite: false
},
{
  id: 418,
  name: "Dhokra Metal Craft",
  category: "Metal & Stone Crafts",
  state: "Chhattisgarh / Odisha",
  shortDescription:"Dhokra Metal Craft is an ancient tribal art known for its handmade brass figures using the lost-wax technique.",
  significance: "Ancient lost-wax metal casting tradition",
  materials: ["Brass"],
  techniques: "Lost-wax casting",
  usage: "Figurines and décor",
  image: "https://d18x2uyjeekruj.cloudfront.net/wp-content/uploads/2022/12/dhokra.jpg",
  isFavorite: false
},
{
  id: 419,
  name: "Bidriware",
  category: "Metal & Stone Crafts",
  state: "Karnataka",
  shortDescription:"Bidriware is a traditional metal craft known for silver inlay on blackened alloy with intricate designs.",
  significance: "Black metal inlay craft with silver designs",
  materials: ["Zinc alloy", "Silver"],
  techniques: "Metal inlay",
  usage: "Decorative vessels",
  image: "https://static.toiimg.com/photo/imgsize-866766,msid-68102322/68102322.jpg",
  isFavorite: false
},
{
  id: 420,
  name: "Brassware of Moradabad",
  category: "Metal & Stone Crafts",
  state: "Uttar Pradesh",
  shortDescription:"Brassware of Moradabad is a traditional metal craft known for its finely engraved brass decorative and utility items.",
  significance: "Brass decorative and utility items",
  materials: ["Brass"],
  techniques: "Casting and engraving",
  usage: "Utensils and décor",
  image: "https://www.dylaa.com/wp-content/uploads/2024/09/Brass-Handicrafts-Dylaa-49.jpg",
  isFavorite: false
},
{
  id: 421,
  name: "Bell Metal Craft",
  category: "Metal & Stone Crafts",
  state: "Assam",
  shortDescription:"Bell Metal Craft is a traditional art known for durable metalware made from a copper-tin alloy.",
  significance: "Traditional alloy metal craft",
  materials: ["Bell metal alloy"],
  techniques: "Casting",
  usage: "Utensils and ritual items",
  image: "https://5.imimg.com/data5/VT/LU/MY-12266299/bell-metal-28dhokra-29-handicrafts.jpg",
  isFavorite: false
},
{
  id: 422,
  name: "Stone Carving",
  category: "Metal & Stone Crafts",
  state: "Odisha",
  shortDescription:"Stone Carving is a traditional craft featuring finely carved sculptures and designs made from natural stone.",
  significance: "Temple sculpture tradition",
  materials:[ "Stone"],
  techniques: "Chiseling",
  usage: "Architecture and idols",
  image: "https://cdn.thestonestudio.in/wp-content/uploads/2023/05/1-feet-vishnu-statue-600x600.png",
  isFavorite: false
},
{
  id: 423,
  name: "Warli Craft Objects",
  category: "Folk & Tribal Crafts",
  state: "Maharashtra",
  shortDescription:"Warli Craft Objects feature simple tribal designs depicting daily life, inspired by traditional Warli art.",
  significance: "Tribal art style depicting daily life",
  materials: [["Clay"], "Natural pigments"],
  techniques: "Hand painting",
  usage: "Decorative art",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTn0fz8_iMi_lFmIx8P2c_cvtykTWCVKR4t1w&s",
  isFavorite: false
},
{
  id: 424,
  name: "Bastar Iron Craft",
  category: "Folk & Tribal Crafts",
  state: "Chhattisgarh",
  shortDescription:"Bastar Iron Craft is a tribal metal art known for handcrafted iron figures inspired by nature and folklore.",
  significance: "Tribal iron craft tradition",
  materials: ["Wrought iron"],
  techniques: "Forging",
  usage: "Decor and tools",
  image: "https://curriculture.in/wp-content/uploads/2025/08/bastar-iron-craft1.jpg",
  isFavorite: false
},
{
  id: 425,
  name: "Toda Embroidery",
  category: "Folk & Tribal Crafts",
  state: "Tamil Nadu",
  shortDescription:"Toda Embroidery is a traditional tribal embroidery from the Nilgiris, known for bold red and black patterns.",
  significance: "Geometric tribal embroidery of Toda tribe",
  materials: ["Cotton", "Wool threads"],
  techniques: "Hand embroidery",
  usage: "Shawls and cloth",
  image: "https://img.perniaspopupshop.com/store-locator-v2/uploads/PWA_Main_Tamil_Nadu_1_f036eb6d7c.jpg",
  isFavorite: false
},
{
  id: 426,
  name: "Santhal Tribal Craft",
  category: "Folk & Tribal Crafts",
  state: "Jharkhand",
  shortDescription:"Santhal Tribal Craft is a folk art known for handcrafted items reflecting tribal life, nature, and cultural traditions.",
  significance: "Tribal craft expressing folklore and nature",
  materials:[ "Natural materials"],
  techniques: "Hand crafting",
  usage: "Decorative items",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRD5DfQRmEGvjq_647rQywS3wYN8E9QfsLIaA&s",
  isFavorite: false
},
{
  id: 427,
  name: "Leather Puppet Craft",
  category: "Folk & Tribal Crafts",
  state: "Andhra Pradesh",
  shortDescription:"Leather Puppet Craft is a traditional art using painted leather to create shadow puppets for storytelling.",
  significance: "Shadow puppetry tradition",
  materials: ["Leather", "Natural dyes"],
  techniques: "Leather cutting and painting",
  usage: "Storytelling performances",
  image: "https://theindiacrafthouse.com/cdn/shop/products/Andhra_Leather_Painted_String_Puppet_Lifesize_58_x_22_-_Lord_Hanuman_-_DHSLPA_1@2x.jpg",
  isFavorite: false
}
  ],
  reducers:{
    toggleLike:(state, action)=>{
      const id = action.payload
      const item = state.find((hand)=> hand.id===id)
      if(item){
        item.isFavorite=!item.isFavorite
      }
    }
  }
})
export const {toggleLike} = HandicraftSlice.actions
export default HandicraftSlice.reducer