import { createSlice } from "@reduxjs/toolkit";

const HandicraftSlice = createSlice({
    name:'handicrafts',
    initialState:[
    {
  id: 401,
  name: "Banarasi Silk Sarees",
  category: "Textiles & Fabrics",
  state: "Uttar Pradesh",
  originCity:"Varanasi",
  historicalPeriod:"16th century",
  giStatus:"Yes",
  craftType:"Textile",
  shortDescription:"Banarasi Silk Sarees are handwoven from rich silk, known for intricate gold and silver zari work.",
  description:"Banarasi Silk Sarees are luxurious handwoven sarees from Varanasi, known for their rich silk fabric, intricate gold and silver zari work, and elegant traditional motifs. They are celebrated for their craftsmanship, vibrant designs, and cultural significance in weddings and festive occasions.",
  significance: "Luxurious silk sarees known for gold and silver brocade work",
  materials: ["Silk",
  "Zari threads"],
  techniques: "Handloom weaving with intricate motifs",
  usage: "Wedding and festive wear",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwSQaa6p_dwftwOCQEEjHTP5fM_3g9vEcZOQ&s",
  isFavorite: false
},
{
  id: 402,
  name: "Kanchipuram Silk",
  category: "Textiles & Fabrics",
  state: "Tamil Nadu",
  originCity:"Kanchipuram",
  historicalPeriod:"2ns century",
  giStatus:"Yes",
  craftType:"Textile",
  shortDescription:"Kanchipuram Silk Sarees are handwoven from pure silk, known for their rich colors and zari work.",
  description:"Kanchipuram Silk Sarees are renowned handwoven silk sarees from Kanchipuram, Tamil Nadu. Known for their vibrant colors, durable silk, and intricate zari work depicting traditional motifs, they are considered a symbol of elegance and are highly valued for weddings and special occasions.",
  significance: "Traditional silk sarees with temple-inspired designs",
  materials: ["Pure mulberry silk",
  "Zari"],
  techniques: "Interlocked weaving technique",
  usage: "Bridal and ceremonial wear",
  image: "https://www.deepam.com/cdn/shop/articles/D216968_1080x_8d6419f4-9e6a-4f99-8a9b-c76bdc4bbe54.webp?v=1707470495",
  isFavorite: false
},
{
  id: 403,
  name: "Pashmina Shawls",
  category: "Textiles & Fabrics",
  state: "Jammu & Kashmir",
  originCity:"Srinagar",
  historicalPeriod:"15th century",
  giStatus:"Yes",
  craftType:"Textile",
  shortDescription:"Pashmina Shawls are soft, luxurious shawls from Kashmir, made from fine wool and for their warmth and elegance.",
  description:"Pashmina Shawls are luxurious handwoven shawls from Kashmir, made from the fine wool of Pashmina goats. They are celebrated for their softness, warmth, intricate embroidery, and delicate patterns, and are considered a symbol of elegance and craftsmanship.",
  significance: "Fine wool shawls known for softness and warmth",
  materials: ["Pashmina wool"],
  techniques: "Hand-spinning and hand-weaving",
  usage: "Luxury winter wear",
  image: "https://sairasboutique.net/cdn/shop/products/DSC_7253-1_1024x1024.jpg?v=1548911649",
  isFavorite: false
},
{
  id: 404,
  name: "Chikankari Embroidery",
  category: "Textiles & Fabrics",
  state: "Uttar Pradesh",
  originCity:"Lucknow",
  historicalPeriod:"Mughal period",
  giStatus:"Yes",
  craftType:"Embroridery",
  shortDescription:"Chikankari Embroidery is a delicate hand embroidery from Lucknow, known for its elegant floral patterns on fine fabrics.",
  description:"Chikankari Embroidery is a delicate hand embroidery style from Lucknow, Uttar Pradesh. Characterized by intricate floral and geometric patterns on lightweight fabrics like muslin and cotton, it is known for its elegance, fine stitches, and timeless appeal in traditional and contemporary garments.",
  significance: "Delicate hand embroidery style from Lucknow",
  materials: ["Cotton", "Silk threads"],
  techniques: "Hand embroidery",
  usage: "Traditional garments",
  image: "https://i.pinimg.com/736x/fa/9f/5b/fa9f5b472f4a45b0d6830bf8e4bcb705.jpg",
  isFavorite: false
},
{
  id: 405,
  name: "Ikat Weaving",
  category: "Textiles & Fabrics",
  state: "Odisha / Telangana",
  originCity:"Odisha / Pochampally",
  historicalPeriod:"Ancient",
  giStatus:"Yes",
  craftType:"Textile",
  shortDescription:"Ikat Weaving is a traditional textile art known for its bold patterns created by resist-dyeing yarns before weaving.",
  description:"Ikat Weaving is a dyeing and weaving technique in which threads are tie-dyed before weaving to create intricate patterns and designs on fabric. Popular in states like Odisha, Andhra Pradesh, and Gujarat, Ikat is known for its vibrant colors, geometric motifs, and cultural significance in traditional garments and textiles.",
  significance: "Resist-dyeing textile technique with blurred patterns",
  materials: ["Cotton", "Silk"],
  techniques: "Yarn resist dyeing",
  usage: "Sarees, fabrics",
  image: "https://mavuris.com/cdn/shop/articles/ikat_saree_83cc090c-26a0-419d-94e2-5714120070f1.jpg?v=1750319188",
  isFavorite: false
},
{
  id: 406,
  name: "Kalamkari Fabric",
  category: "Textiles & Fabrics",
  state: "Andhra Pradesh",
  originCity:"Machilipatnam / Srikalahasti",
  historicalPeriod:"17th century",
  giStatus:"Yes",
  craftType:"Textile",
  shortDescription:"Kalamkari Fabric is a hand-painted or block-printed textile known for its natural dyes and mythological motifs.",
  description:"Kalamkari Fabric is a hand-painted or block-printed fabric from Andhra Pradesh, featuring intricate designs and mythological themes. Created using natural dyes, it is known for its vibrant colors, detailed storytelling motifs, and use in garments, home décor, and traditional art forms.",
  significance: "Hand-painted or block-printed textile art",
  materials: ["Cotton", "Natural dyes"],
  techniques: "Freehand drawing with pen",
  usage: "Wall hangings, garments",
  image: "https://www.vemshala.com/cdn/shop/files/natural-multi-floral-gold-pen-kalamkari-tussar-silk-saree-141759.jpg?v=1739427746",
  isFavorite: false
},
{
  id: 407,
  name: "Phulkari Embroidery",
  category: "Textiles & Fabrics",
  state: "Punjab",
  originCity:"Punjab",
  historicalPeriod:"15th - 16 th century",
  giStatus:"Yes",
  craftType:"Embroidery",
  shortDescription:"Phulkari Embroidery is a vibrant Punjabi folk art known for its colorful geometric floral patterns stitched on fabric.",
  description:"Phulkari Embroidery is a traditional embroidery art from Punjab, characterized by vibrant floral patterns stitched onto cotton or khaddar fabric using silk threads. Often used in shawls, dupattas, and garments, it symbolizes cultural heritage, celebration, and craftsmanship.",
  significance: "Vibrant floral embroidery tradition",
  materials: ["Cotton fabric", "Silk thread"],
  techniques: "Darning stitch embroidery",
  usage: "Dupattas and shawls",
  image: "https://i.pinimg.com/736x/25/da/26/25da26aca2f7b0bedccac0bc7644cfa2.jpg",
  isFavorite: false
},
{
  id: 408,
  name: "Blue Pottery",
  category: "Pottery & Clay Crafts",
  state: "Rajasthan",
  originCity:"Jaipur",
  historicalPeriod:"14th–15th century",
  giStatus:"Yes",
  craftType:"Pottery",
  shortDescription:"Blue Pottery is a traditional ceramic art known for its blue-and-white floral designs and delicate craftsmanship.",
  description:"Blue Pottery is a distinctive craft from Jaipur, Rajasthan, known for its bright blue and white floral patterns on earthenware. Made using a unique technique with quartz, it produces delicate yet durable pottery items like tiles, vases, and decorative pieces, reflecting India’s rich artisanal heritage.",
  significance: "Distinctive blue-glazed pottery",
  materials: ["Quartz", "Glass", "Multani Mitti"],
  techniques: "Glazing and low-temperature firing",
  usage: "Decorative items",
  image: "https://c9admin.cottage9.com/uploads/2322/image_2023_01_20T09_08_11_450Z-1024x723.png",
  isFavorite: false
},
{
  id: 409,
  name: "Terracotta Art",
  category: "Pottery & Clay Crafts",
  state: "West Bengal",
  originCity:"Across India",
  historicalPeriod:"Ancient",
  giStatus:"No",
  craftType:"Pottery / Sculpture",
  shortDescription:"Terracotta Art is a traditional clay craft known for its earthy tones and handcrafted figurines, pots, and decor.",
  description:"Terracotta Art is an ancient Indian craft of shaping and baking clay to create pottery, sculptures, and decorative items. Practiced across various regions, it features earthy tones, intricate designs, and motifs inspired by nature, mythology, and daily life, reflecting cultural traditions and artisanal skills.",
  significance: "Ancient clay craft used in temples and décor",
  materials: ["Natural clay"],
  techniques: "Hand molding and firing",
  usage: "Sculptures and tiles",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVvs3JvRrPBRMYuTz-QEgs_sGKW-UQj424eA&s",
  isFavorite: false
},
{
  id: 410,
  name: "Molela Clay Work",
  category: "Pottery & Clay Crafts",
  state: "Rajasthan",
  originCity:"Molela",
  historicalPeriod:"18 th century",
  giStatus:"No",
  craftType:"Pottery",
  shortDescription:"Molela Clay Work is a traditional Rajasthan craft featuring handcrafted clay plaques of folk motifs.",
  description:"Molela Clay Work is a traditional clay craft from Molela village in Rajasthan. Artisans create decorative terracotta items such as figurines, diyas, and miniature sculptures, often painted in vibrant colors, reflecting the cultural heritage and folk traditions of the region.",
  significance: "Raised clay relief work depicting folk deities",
  materials: ["Clay"],
  techniques: "Relief molding",
  usage: "Shrines and wall décor",
  image: "https://i.pinimg.com/736x/80/4e/ff/804eff453406ef035d2b51e7ab4a0286.jpg",
  isFavorite: false
},
{
  id: 411,
  name: "Black Pottery",
  category: "Pottery & Clay Crafts",
  state: "Manipur",
  originCity:"Mnipur",
  historicalPeriod:"12th century",
  giStatus:"No",
  craftType:"Pottery",
  shortDescription:"Black Pottery is a traditional craft known for its smooth black finish and simple, elegant designs.",
  description:"Black Pottery is a unique pottery art from Manipur, known for its distinctive black color achieved through a special firing technique. Artisans create functional and decorative items with smooth finishes and intricate designs, reflecting the region’s traditional craftsmanship and cultural heritage.",
  significance: "Smoky black-finished traditional pottery",
  materials: ["Clay"],
  techniques: "Smoke firing",
  usage: "Utensils and décor",
  image: "https://divya.lovestoblog.com/wp-content/uploads/2024/08/web10-1.png",
  isFavorite: false
},
{
  id: 412,
  name: "Khurja Pottery",
  category: "Pottery & Clay Crafts",
  state: "Uttar Pradesh",
  originCity:"Khurja",
  historicalPeriod:"14th century",
  giStatus:"Yes",
  craftType:"Pottery",
  shortDescription:"Khurja Pottery is a traditional ceramic craft known for its colorful glazes and hand-painted designs.",
  description:"Khurja Pottery is a renowned ceramic craft from Khurja, Uttar Pradesh, known for its vibrant hand-painted designs on earthenware. The pottery includes tiles, tableware, and decorative items, often featuring floral motifs, bright colors, and a glossy finish, reflecting India’s rich ceramic heritage.",
  significance: "Famous for glazed ceramic pottery",
  materials: ["Clay"],
  techniques: "Wheel throwing and glazing",
  usage: "Tableware and décor",
  image: "https://i.pinimg.com/1200x/32/cc/51/32cc51eb06203ef1df6bc43338ef62b6.jpg",
  isFavorite: false
},
{
  id: 413,
  name: "Sandalwood Carving",
  category: "Wood & Bamboo Crafts",
  state: "Karnataka",
  originCity:"Mysore",
  historicalPeriod:"17th century",
  giStatus:"Yes",
  craftType:"Wood Craft",
  shortDescription:"Sandalwood Carving is a traditional craft known for its natural fragrance, and intricate designs.",
  description:"Sandalwood Carving is a traditional craft from Karnataka, involving intricate carving of aromatic sandalwood to create decorative items, religious idols, and sculptures. Renowned for its fine detailing and smooth finish, it reflects the region’s artistic heritage and skilled craftsmanship.",
  significance: "Fine carving on fragrant sandalwood",
  materials: ["Sandalwood"],
  techniques: "Hand carving",
  usage: "Statues and artifacts",
  image: "https://www.maljiarts.in/cdn/shop/files/IMG_2810.heic?v=1748521779&width=1946",
  isFavorite: false
},
{
  id: 414,
  name: "Rosewood Inlay",
  category: "Wood & Bamboo Crafts",
  state: "Kerala",
  originCity:"Mysore",
  historicalPeriod:"18th century",
  giStatus:"Yes",
  craftType:"Wood Craft",
  shortDescription:"Rosewood Inlay is a traditional craft featuring intricate inlaid patterns on polished rosewood surfaces.",
  description:"Rosewood Inlay is a skilled woodworking craft from Karnataka, where rosewood surfaces are inlaid with materials like ivory, metal, or colored stones to create intricate decorative patterns. It is commonly used for furniture, jewelry boxes, and ornamental items, showcasing exquisite artistry and precision.",
  significance: "Decorative wooden inlay craft",
  materials: ["Rosewood", "ivory substitutes"],
  techniques: "Inlay work",
  usage: "Furniture and décor",
  image: "https://upload.wikimedia.org/wikipedia/commons/2/2b/Wood_inlay_Mysore.jpg",
  isFavorite: false
},
{
  id: 415,
  name: "Bamboo Craft",
  category: "Wood & Bamboo Crafts",
  state: "North East India",
  originCity:"Across India",
  historicalPeriod:"Ancient",
  giStatus:"No",
  craftType:"Handicraft",
  shortDescription:"Bamboo Craft is a traditional art using bamboo to create eco-friendly baskets, decor, and utility items.",
  description:"Bamboo Craft is a traditional Indian craft that uses bamboo to create functional and decorative items such as baskets, mats, furniture, and utensils. Known for its eco-friendly nature, durability, and intricate weaving techniques, it reflects the craftsmanship and cultural heritage of various tribal and rural communities.",
  significance: "Eco-friendly traditional bamboo items",
  materials: ["Bamboo"],
  techniques: "Weaving and binding",
  usage: "Household items",
  image: "https://5.imimg.com/data5/IH/OU/MY-12266299/bamboo-work-handicraft.jpg",
  isFavorite: false
},
{
  id: 416,
  name: "Saharanpur Woodcraft",
  category: "Wood & Bamboo Crafts",
  state: "Uttar Pradesh",
  originCity:"Saharanpur",
  historicalPeriod:"17th century",
  giStatus:"Yes",
  craftType:"Wood Craft",
  shortDescription:"Saharanpur Wood Carving is a traditional craft known for its intricate floral and geometric designs carved in wood.",
  description:"Saharanpur Woodcraft is a renowned woodworking craft from Saharanpur, Uttar Pradesh, known for its intricate carvings and polished finishes. Artisans create furniture, decorative items, and wooden panels featuring floral and geometric designs, reflecting the region’s rich artistic heritage.",
  significance: "Detailed floral wood carving",
  materials: ["Sheesham wood"],
  techniques: "Hand carving",
  usage: "Furniture and décor",
  image: "https://aarsunwoods.com/wp-content/uploads/2017/09/Pooja-Cabinet-Wood-Temple-in-Teak-Wood-UH-YT-145.jpg",
  isFavorite: false
},
{
  id: 417,
  name: "Channapatna Toys",
  category: "Wood & Bamboo Crafts",
  state: "Karnataka",
  originCity:"Channapatna",
  historicalPeriod:"17th century",
  giStatus:"Yes",
  craftType:"Toys",
  shortDescription:"Channapatna Toys are traditional wooden toys known for their bright colors, smooth finish, and lac coating.",
  description:"Channapatna Toys are colorful wooden toys and dolls from Channapatna, Karnataka, made using traditional lacquering and turning techniques. Known as the “Gombegala Ooru” (toy town), this craft combines vibrant colors, smooth finishes, and safe, eco-friendly materials, reflecting India’s folk art and heritage.",
  significance: "Colorful eco-friendly wooden toys",
  materials: ["Softwood", "natural dyes"],
  techniques: "Lac-turning",
  usage: "Toys and décor",
  image: "https://storeassets.im-cdn.com/media-manager/channapatnatoysin/280eU8ASIK3BTw3yHkER_channapatna%20toys%20banner%2015_621x375_webp.jpg",
  isFavorite: false
},
{
  id: 418,
  name: "Dhokra Metal Craft",
  category: "Metal & Stone Crafts",
  state: "Chhattisgarh / Odisha",
  originCity:"West Bengal / Odisha / Chhattisgarh",
  historicalPeriod:"Ancient",
  giStatus:"Yes",
  craftType:"Metalwork",
  shortDescription:"Dhokra Metal Craft is an ancient tribal art known for its handmade brass figures using the lost-wax technique.",
  description:"Dhokra Metal Craft is an ancient metal casting art practiced by tribal communities in India, especially in West Bengal, Odisha, and Chhattisgarh. Using the lost-wax technique, artisans create intricate brass and bell metal figures, including animals, deities, and decorative items, reflecting traditional craftsmanship and tribal culture.",
  significance: "Ancient lost-wax metal casting tradition",
  materials: ["Brass"],
  techniques: "Lost-wax casting",
  usage: "Figurines and décor",
  image: "https://d18x2uyjeekruj.cloudfront.net/wp-content/uploads/2022/12/dhokra.jpg",
  isFavorite: false
},
{
  id: 419,
  name: "Bidriware",
  category: "Metal & Stone Crafts",
  state: "Karnataka",
  originCity:"Bidar",
  historicalPeriod:"14th - 15th century",
  giStatus:"Yes",
  craftType:"Metalwork",
  shortDescription:"Bidriware is a traditional metal craft known for silver inlay on blackened alloy with intricate designs.",
  description:"Bidriware is a metal inlay craft from Bidar, Karnataka, known for its blackened alloy base inlaid with silver or brass. Artisans create decorative items like vases, trays, and jewelry with intricate patterns, reflecting the rich Indo-Islamic heritage and skilled craftsmanship of the region.",
  significance: "Black metal inlay craft with silver designs",
  materials: ["Zinc alloy", "Silver"],
  techniques: "Metal inlay",
  usage: "Decorative vessels",
  image: "https://static.toiimg.com/photo/imgsize-866766,msid-68102322/68102322.jpg",
  isFavorite: false
},
{
  id: 420,
  name: "Brassware of Moradabad",
  category: "Metal & Stone Crafts",
  state: "Uttar Pradesh",
  originCity:"Moradabad",
  historicalPeriod:"17th century",
  giStatus:"Yes",
  craftType:"Metalwork",
  shortDescription:"Brassware of Moradabad is a traditional metal craft known for its finely engraved brass decorative and utility items.",
  description:"Brassware of Moradabad is a renowned handicraft from Moradabad, Uttar Pradesh, known for its intricate brass items such as utensils, decorative pieces, and sculptures. Often featuring detailed engravings and polished finishes, it reflects the city’s rich metalworking heritage and artisanal expertise.",
  significance: "Brass decorative and utility items",
  materials: ["Brass"],
  techniques: "Casting and engraving",
  usage: "Utensils and décor",
  image: "https://www.dylaa.com/wp-content/uploads/2024/09/Brass-Handicrafts-Dylaa-49.jpg",
  isFavorite: false
},
{
  id: 421,
  name: "Bell Metal Craft",
  category: "Metal & Stone Crafts",
  state: "Assam",
  originCity:"Assam / Odisha / Chhattisgarh",
  historicalPeriod:"Ancient",
  giStatus:"No",
  craftType:"Metalwork",
  shortDescription:"Bell Metal Craft is a traditional art known for durable metalware made from a copper-tin alloy.",
  description:"Bell Metal Craft is a traditional Indian metal craft using an alloy of copper and tin (bell metal) to create utensils, statues, and decorative items. Practiced in states like Assam, Odisha, and Chhattisgarh, it is known for its durability, resonant sound, and intricate designs reflecting cultural and religious heritage.",
  significance: "Traditional alloy metal craft",
  materials: ["Bell metal alloy"],
  techniques: "Casting",
  usage: "Utensils and ritual items",
  image: "https://5.imimg.com/data5/VT/LU/MY-12266299/bell-metal-28dhokra-29-handicrafts.jpg",
  isFavorite: false
},
{
  id: 422,
  name: "Stone Carving",
  category: "Metal & Stone Crafts",
  state: "Odisha",
  originCity:"Across India",
  historicalPeriod:"Ancient",
  giStatus:"No",
  craftType:"Sculpture",
  shortDescription:"Stone Carving is a traditional craft featuring finely carved sculptures and designs made from natural stone.",
  description:"Stone Carving is an ancient Indian craft involving shaping and sculpting stone to create temples, idols, architectural elements, and decorative pieces. Practiced across India, it features intricate designs, motifs from mythology, and skilled craftsmanship, reflecting the country’s rich cultural and artistic heritage.",
  significance: "Temple sculpture tradition",
  materials:[ "Stone"],
  techniques: "Chiseling",
  usage: "Architecture and idols",
  image: "https://cdn.thestonestudio.in/wp-content/uploads/2023/05/1-feet-vishnu-statue-600x600.png",
  isFavorite: false
},
{
  id: 423,
  name: "Warli Craft Objects",
  category: "Folk & Tribal Crafts",
  state: "Maharashtra",
  originCity:"Maharashtra",
  historicalPeriod:"Ancient",
  giStatus:"No",
  craftType:"Paiting / Handicraft",
  shortDescription:"Warli Craft Objects feature simple tribal designs depicting daily life, inspired by traditional Warli art.",
  description:"Warli Craft Objects are traditional handcrafted items made by the Warli tribe of Maharashtra, inspired by their famous Warli paintings. These objects, such as decorative panels, pottery, and wall art, feature geometric patterns and motifs depicting daily life, nature, and tribal rituals, reflecting the community’s artistic heritage.",
  significance: "Tribal art style depicting daily life",
  materials: [["Clay"], "Natural pigments"],
  techniques: "Hand painting",
  usage: "Decorative art",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTn0fz8_iMi_lFmIx8P2c_cvtykTWCVKR4t1w&s",
  isFavorite: false
},
{
  id: 424,
  name: "Bastar Iron Craft",
  category: "Folk & Tribal Crafts",
  state: "Chhattisgarh",
  originCity:"Bastar",
  historicalPeriod:"Ancient",
  giStatus:"No",
  craftType:"Metalwork",
  shortDescription:"Bastar Iron Craft is a tribal metal art known for handcrafted iron figures inspired by nature and folklore.",
  description:"Bastar Iron Craft is a traditional metalworking craft of the Bastar region in Chhattisgarh. Artisans create functional and decorative items from wrought iron, including tools, weapons, and sculptures, often featuring tribal motifs and intricate designs, reflecting the region’s cultural heritage and artisanal skills.",
  significance: "Tribal iron craft tradition",
  materials: ["Wrought iron"],
  techniques: "Forging",
  usage: "Decor and tools",
  image: "https://curriculture.in/wp-content/uploads/2025/08/bastar-iron-craft1.jpg",
  isFavorite: false
},
{
  id: 425,
  name: "Toda Embroidery",
  category: "Folk & Tribal Crafts",
  state: "Tamil Nadu",
  originCity:"Nilgiris",
  historicalPeriod:"19th century",
  giStatus:"No",
  craftType:"Metalwork",
  shortDescription:"Toda Embroidery is a traditional tribal embroidery from the Nilgiris, known for bold red and black patterns.",
  description:"Toda Embroidery is a traditional textile craft of the Toda community from the Nilgiri Hills in Tamil Nadu. It is known for its distinctive red and black geometric patterns on white fabric, primarily used in shawls and garments, reflecting the tribe’s cultural identity and artisanal heritage.",
  significance: "Geometric tribal embroidery of Toda tribe",
  materials: ["Cotton", "Wool threads"],
  techniques: "Hand embroidery",
  usage: "Shawls and cloth",
  image: "https://img.perniaspopupshop.com/store-locator-v2/uploads/PWA_Main_Tamil_Nadu_1_f036eb6d7c.jpg",
  isFavorite: false
},
{
  id: 426,
  name: "Santhal Tribal Craft",
  category: "Folk & Tribal Crafts",
  state: "Jharkhand",
  originCity:"Jharkhand",
  historicalPeriod:"Ancient",
  giStatus:"No",
  craftType:"Painting / Handicraft",
  shortDescription:"Santhal Tribal Craft is a folk art known for handcrafted items reflecting tribal life, nature, and cultural traditions.",
  description:"Santhal Tribal Craft is a traditional craft of the Santhal community in Jharkhand, encompassing painting, pottery, weaving, and decorative items. These crafts often feature vibrant colors, geometric patterns, and motifs inspired by nature and tribal life, reflecting the community’s cultural heritage and artisanal skills.",
  significance: "Tribal craft expressing folklore and nature",
  materials:[ "Natural materials"],
  techniques: "Hand crafting",
  usage: "Decorative items",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRD5DfQRmEGvjq_647rQywS3wYN8E9QfsLIaA&s",
  isFavorite: false
},
{
  id: 427,
  name: "Leather Puppet Craft",
  category: "Folk & Tribal Crafts",
  state: "Andhra Pradesh",
  originCity:"Andhra Pradesh",
  historicalPeriod:"Ancient",
  giStatus:"No",
  craftType:"Puppetry",
  shortDescription:"Leather Puppet Craft is a traditional art using painted leather to create shadow puppets for storytelling.",
  description:"Leather Puppet Craft is a traditional folk art of Rajasthan, where artisans create colorful puppets from leather to narrate stories from epics like the Ramayana and Mahabharata. Used in puppet shows (Kathputli), these crafts feature intricate painting, vibrant colors, and articulated limbs, reflecting India’s rich storytelling heritage.",
  significance: "Shadow puppetry tradition",
  materials: ["Leather", "Natural dyes"],
  techniques: "Leather cutting and painting",
  usage: "Storytelling performances",
  image: "https://theindiacrafthouse.com/cdn/shop/products/Andhra_Leather_Painted_String_Puppet_Lifesize_58_x_22_-_Lord_Hanuman_-_DHSLPA_1@2x.jpg",
  isFavorite: false
}
  ],
  reducers:{
    toggleLike:(state, action)=>{
      const id = action.payload
      const item = state.find((hand)=> hand.id===id)
      if(item){
        item.isFavorite=!item.isFavorite
      }
    }
  }
})
export const {toggleLike} = HandicraftSlice.actions
export default HandicraftSlice.reducer